// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using MonoSlice.Modules.Users.Domain;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MonoSlice.Modules.Users.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ApplicationRoleEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "MonoSlice.Modules.Users.Domain.ApplicationRole",
                typeof(ApplicationRole),
                baseEntityType,
                propertyCount: 5,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(IdentityRole<Guid>).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityRole<Guid>).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (ApplicationRole instance) => IdentityRoleUnsafeAccessors<Guid>.Id(instance),
                bool (ApplicationRole instance) => IdentityRoleUnsafeAccessors<Guid>.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                ApplicationRole (ApplicationRole instance, Guid value) =>
                {
                    IdentityRoleUnsafeAccessors<Guid>.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                ApplicationRole (ApplicationRole instance, Guid value) =>
                {
                    IdentityRoleUnsafeAccessors<Guid>.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && IdentityRoleUnsafeAccessors<Guid>.Id(((ApplicationRole)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : IdentityRoleUnsafeAccessors<Guid>.Id(((ApplicationRole)(entry.Entity))))),
                Guid (IInternalEntry entry) => IdentityRoleUnsafeAccessors<Guid>.Id(((ApplicationRole)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var concurrencyStamp = runtimeEntityType.AddProperty(
                "ConcurrencyStamp",
                typeof(string),
                propertyInfo: typeof(IdentityRole<Guid>).GetProperty("ConcurrencyStamp", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityRole<Guid>).GetField("<ConcurrencyStamp>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                concurrencyToken: true);
            concurrencyStamp.SetGetter(
                string (ApplicationRole instance) => IdentityRoleUnsafeAccessors<Guid>.ConcurrencyStamp(instance),
                bool (ApplicationRole instance) => IdentityRoleUnsafeAccessors<Guid>.ConcurrencyStamp(instance) == null);
            concurrencyStamp.SetSetter(
                ApplicationRole (ApplicationRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<Guid>.ConcurrencyStamp(instance) = value;
                    return instance;
                });
            concurrencyStamp.SetMaterializationSetter(
                ApplicationRole (ApplicationRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<Guid>.ConcurrencyStamp(instance) = value;
                    return instance;
                });
            concurrencyStamp.SetAccessors(
                string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<Guid>.ConcurrencyStamp(((ApplicationRole)(entry.Entity))),
                string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<Guid>.ConcurrencyStamp(((ApplicationRole)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(concurrencyStamp, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(concurrencyStamp));
            concurrencyStamp.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            concurrencyStamp.TypeMapping = StringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    dbType: System.Data.DbType.String));
            concurrencyStamp.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(ApplicationRole).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApplicationRole).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 256);
            description.SetGetter(
                string (ApplicationRole instance) => ApplicationRoleUnsafeAccessors.Description(instance),
                bool (ApplicationRole instance) => ApplicationRoleUnsafeAccessors.Description(instance) == null);
            description.SetSetter(
                ApplicationRole (ApplicationRole instance, string value) =>
                {
                    ApplicationRoleUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetMaterializationSetter(
                ApplicationRole (ApplicationRole instance, string value) =>
                {
                    ApplicationRoleUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetAccessors(
                string (IInternalEntry entry) => ApplicationRoleUnsafeAccessors.Description(((ApplicationRole)(entry.Entity))),
                string (IInternalEntry entry) => ApplicationRoleUnsafeAccessors.Description(((ApplicationRole)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(description, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(description));
            description.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            description.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "character varying(256)",
                    size: 256));
            description.TypeMapping = ((NpgsqlStringTypeMapping)description.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
        description.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var name = runtimeEntityType.AddProperty(
            "Name",
            typeof(string),
            propertyInfo: typeof(IdentityRole<Guid>).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(IdentityRole<Guid>).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            nullable: true,
            maxLength: 256);
        name.SetGetter(
            string (ApplicationRole instance) => IdentityRoleUnsafeAccessors<Guid>.Name(instance),
            bool (ApplicationRole instance) => IdentityRoleUnsafeAccessors<Guid>.Name(instance) == null);
        name.SetSetter(
            ApplicationRole (ApplicationRole instance, string value) =>
            {
                IdentityRoleUnsafeAccessors<Guid>.Name(instance) = value;
                return instance;
            });
        name.SetMaterializationSetter(
            ApplicationRole (ApplicationRole instance, string value) =>
            {
                IdentityRoleUnsafeAccessors<Guid>.Name(instance) = value;
                return instance;
            });
        name.SetAccessors(
            string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<Guid>.Name(((ApplicationRole)(entry.Entity))),
            string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<Guid>.Name(((ApplicationRole)(entry.Entity))),
            string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 3),
            string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
        name.SetPropertyIndexes(
            index: 3,
            originalValueIndex: 3,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        name.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
            comparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            keyComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            providerValueComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "character varying(256)",
                size: 256));
        name.TypeMapping = ((NpgsqlStringTypeMapping)name.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
    name.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var normalizedName = runtimeEntityType.AddProperty(
        "NormalizedName",
        typeof(string),
        propertyInfo: typeof(IdentityRole<Guid>).GetProperty("NormalizedName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(IdentityRole<Guid>).GetField("<NormalizedName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        nullable: true,
        maxLength: 256);
    normalizedName.SetGetter(
        string (ApplicationRole instance) => IdentityRoleUnsafeAccessors<Guid>.NormalizedName(instance),
        bool (ApplicationRole instance) => IdentityRoleUnsafeAccessors<Guid>.NormalizedName(instance) == null);
    normalizedName.SetSetter(
        ApplicationRole (ApplicationRole instance, string value) =>
        {
            IdentityRoleUnsafeAccessors<Guid>.NormalizedName(instance) = value;
            return instance;
        });
    normalizedName.SetMaterializationSetter(
        ApplicationRole (ApplicationRole instance, string value) =>
        {
            IdentityRoleUnsafeAccessors<Guid>.NormalizedName(instance) = value;
            return instance;
        });
    normalizedName.SetAccessors(
        string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<Guid>.NormalizedName(((ApplicationRole)(entry.Entity))),
        string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<Guid>.NormalizedName(((ApplicationRole)(entry.Entity))),
        string (IInternalEntry entry) => entry.ReadOriginalValue<string>(normalizedName, 4),
        string (IInternalEntry entry) => entry.GetCurrentValue<string>(normalizedName));
    normalizedName.SetPropertyIndexes(
        index: 4,
        originalValueIndex: 4,
        shadowIndex: -1,
        relationshipIndex: -1,
        storeGenerationIndex: -1);
    normalizedName.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
        comparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        keyComparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        providerValueComparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        mappingInfo: new RelationalTypeMappingInfo(
            storeTypeName: "character varying(256)",
            size: 256));
    normalizedName.TypeMapping = ((NpgsqlStringTypeMapping)normalizedName.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
normalizedName.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(normalizedName));
normalizedName.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var key = runtimeEntityType.AddKey(
    new[] { id });
runtimeEntityType.SetPrimaryKey(key);

var index = runtimeEntityType.AddIndex(
    new[] { normalizedName },
    unique: true);
index.AddAnnotation("Relational:Name", "RoleNameIndex");

return runtimeEntityType;
}

public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
{
    var id = runtimeEntityType.FindProperty("Id");
    var concurrencyStamp = runtimeEntityType.FindProperty("ConcurrencyStamp");
    var description = runtimeEntityType.FindProperty("Description");
    var name = runtimeEntityType.FindProperty("Name");
    var normalizedName = runtimeEntityType.FindProperty("NormalizedName");
    var key = runtimeEntityType.FindKey(new[] { id });
    key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
    key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
    runtimeEntityType.SetOriginalValuesFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType = ((ApplicationRole)(source.Entity));
            return ((ISnapshot)(new Snapshot<Guid, string, string, string, string>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), (source.GetCurrentValue<string>(concurrencyStamp) == null ? null : ((ValueComparer<string>)(((IProperty)concurrencyStamp).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(concurrencyStamp))), (source.GetCurrentValue<string>(description) == null ? null : ((ValueComparer<string>)(((IProperty)description).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(description))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), (source.GetCurrentValue<string>(normalizedName) == null ? null : ((ValueComparer<string>)(((IProperty)normalizedName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(normalizedName))))));
        });
    runtimeEntityType.SetStoreGeneratedValuesFactory(
        ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid))))));
    runtimeEntityType.SetTemporaryValuesFactory(
        ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
    runtimeEntityType.SetShadowValuesFactory(
        ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
    runtimeEntityType.SetEmptyShadowValuesFactory(
        ISnapshot () => Snapshot.Empty);
    runtimeEntityType.SetRelationshipSnapshotFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType = ((ApplicationRole)(source.Entity));
            return ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)))));
        });
    runtimeEntityType.SetCounts(new PropertyCounts(
        propertyCount: 5,
        navigationCount: 0,
        complexPropertyCount: 0,
        complexCollectionCount: 0,
        originalValueCount: 5,
        shadowCount: 0,
        relationshipCount: 1,
        storeGeneratedCount: 1));
    runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
    runtimeEntityType.AddAnnotation("Relational:Schema", "users");
    runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
    runtimeEntityType.AddAnnotation("Relational:TableName", "Roles");
    runtimeEntityType.AddAnnotation("Relational:ViewName", null);
    runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

    Customize(runtimeEntityType);
}

static partial void Customize(RuntimeEntityType runtimeEntityType);
}
}
