// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using MonoSlice.Modules.Users.Domain;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MonoSlice.Modules.Users.Persistence.CompiledModels
{
    public static class ApplicationUserUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(ApplicationUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FirstName>k__BackingField")]
        public static extern ref string FirstName(ApplicationUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastName>k__BackingField")]
        public static extern ref string LastName(ApplicationUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RefreshToken>k__BackingField")]
        public static extern ref string RefreshToken(ApplicationUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RefreshTokenExpiryTime>k__BackingField")]
        public static extern ref DateTime? RefreshTokenExpiryTime(ApplicationUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UpdatedAt>k__BackingField")]
        public static extern ref DateTime? UpdatedAt(ApplicationUser @this);
    }
}
