// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using MonoSlice.Modules.Users.Domain;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MonoSlice.Modules.Users.Persistence.CompiledModels
{
    public static class ApplicationRoleUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(ApplicationRole @this);
    }
}
