// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MonoSlice.Modules.Users.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class IdentityUserLoginEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>",
                typeof(IdentityUserLogin<Guid>),
                baseEntityType,
                propertyCount: 4,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var loginProvider = runtimeEntityType.AddProperty(
                "LoginProvider",
                typeof(string),
                propertyInfo: typeof(IdentityUserLogin<Guid>).GetProperty("LoginProvider", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserLogin<Guid>).GetField("<LoginProvider>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            loginProvider.SetGetter(
                string (IdentityUserLogin<Guid> instance) => IdentityUserLoginUnsafeAccessors<Guid>.LoginProvider(instance),
                bool (IdentityUserLogin<Guid> instance) => IdentityUserLoginUnsafeAccessors<Guid>.LoginProvider(instance) == null);
            loginProvider.SetSetter(
                IdentityUserLogin<Guid> (IdentityUserLogin<Guid> instance, string value) =>
                {
                    IdentityUserLoginUnsafeAccessors<Guid>.LoginProvider(instance) = value;
                    return instance;
                });
            loginProvider.SetMaterializationSetter(
                IdentityUserLogin<Guid> (IdentityUserLogin<Guid> instance, string value) =>
                {
                    IdentityUserLoginUnsafeAccessors<Guid>.LoginProvider(instance) = value;
                    return instance;
                });
            loginProvider.SetAccessors(
                string (IInternalEntry entry) => IdentityUserLoginUnsafeAccessors<Guid>.LoginProvider(((IdentityUserLogin<Guid>)(entry.Entity))),
                string (IInternalEntry entry) => IdentityUserLoginUnsafeAccessors<Guid>.LoginProvider(((IdentityUserLogin<Guid>)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(loginProvider, 0),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(loginProvider, 0));
            loginProvider.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            loginProvider.TypeMapping = StringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    dbType: System.Data.DbType.String));
            loginProvider.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(loginProvider));
            loginProvider.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var providerKey = runtimeEntityType.AddProperty(
                "ProviderKey",
                typeof(string),
                propertyInfo: typeof(IdentityUserLogin<Guid>).GetProperty("ProviderKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserLogin<Guid>).GetField("<ProviderKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            providerKey.SetGetter(
                string (IdentityUserLogin<Guid> instance) => IdentityUserLoginUnsafeAccessors<Guid>.ProviderKey(instance),
                bool (IdentityUserLogin<Guid> instance) => IdentityUserLoginUnsafeAccessors<Guid>.ProviderKey(instance) == null);
            providerKey.SetSetter(
                IdentityUserLogin<Guid> (IdentityUserLogin<Guid> instance, string value) =>
                {
                    IdentityUserLoginUnsafeAccessors<Guid>.ProviderKey(instance) = value;
                    return instance;
                });
            providerKey.SetMaterializationSetter(
                IdentityUserLogin<Guid> (IdentityUserLogin<Guid> instance, string value) =>
                {
                    IdentityUserLoginUnsafeAccessors<Guid>.ProviderKey(instance) = value;
                    return instance;
                });
            providerKey.SetAccessors(
                string (IInternalEntry entry) => IdentityUserLoginUnsafeAccessors<Guid>.ProviderKey(((IdentityUserLogin<Guid>)(entry.Entity))),
                string (IInternalEntry entry) => IdentityUserLoginUnsafeAccessors<Guid>.ProviderKey(((IdentityUserLogin<Guid>)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(providerKey, 1),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(providerKey, 1));
            providerKey.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            providerKey.TypeMapping = StringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    dbType: System.Data.DbType.String));
            providerKey.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(providerKey));
            providerKey.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var providerDisplayName = runtimeEntityType.AddProperty(
                "ProviderDisplayName",
                typeof(string),
                propertyInfo: typeof(IdentityUserLogin<Guid>).GetProperty("ProviderDisplayName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserLogin<Guid>).GetField("<ProviderDisplayName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            providerDisplayName.SetGetter(
                string (IdentityUserLogin<Guid> instance) => IdentityUserLoginUnsafeAccessors<Guid>.ProviderDisplayName(instance),
                bool (IdentityUserLogin<Guid> instance) => IdentityUserLoginUnsafeAccessors<Guid>.ProviderDisplayName(instance) == null);
            providerDisplayName.SetSetter(
                IdentityUserLogin<Guid> (IdentityUserLogin<Guid> instance, string value) =>
                {
                    IdentityUserLoginUnsafeAccessors<Guid>.ProviderDisplayName(instance) = value;
                    return instance;
                });
            providerDisplayName.SetMaterializationSetter(
                IdentityUserLogin<Guid> (IdentityUserLogin<Guid> instance, string value) =>
                {
                    IdentityUserLoginUnsafeAccessors<Guid>.ProviderDisplayName(instance) = value;
                    return instance;
                });
            providerDisplayName.SetAccessors(
                string (IInternalEntry entry) => IdentityUserLoginUnsafeAccessors<Guid>.ProviderDisplayName(((IdentityUserLogin<Guid>)(entry.Entity))),
                string (IInternalEntry entry) => IdentityUserLoginUnsafeAccessors<Guid>.ProviderDisplayName(((IdentityUserLogin<Guid>)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(providerDisplayName, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(providerDisplayName));
            providerDisplayName.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            providerDisplayName.TypeMapping = StringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    dbType: System.Data.DbType.String));
            providerDisplayName.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var userId = runtimeEntityType.AddProperty(
                "UserId",
                typeof(Guid),
                propertyInfo: typeof(IdentityUserLogin<Guid>).GetProperty("UserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserLogin<Guid>).GetField("<UserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            userId.SetGetter(
                Guid (IdentityUserLogin<Guid> instance) => IdentityUserLoginUnsafeAccessors<Guid>.UserId(instance),
                bool (IdentityUserLogin<Guid> instance) => IdentityUserLoginUnsafeAccessors<Guid>.UserId(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            userId.SetSetter(
                IdentityUserLogin<Guid> (IdentityUserLogin<Guid> instance, Guid value) =>
                {
                    IdentityUserLoginUnsafeAccessors<Guid>.UserId(instance) = value;
                    return instance;
                });
            userId.SetMaterializationSetter(
                IdentityUserLogin<Guid> (IdentityUserLogin<Guid> instance, Guid value) =>
                {
                    IdentityUserLoginUnsafeAccessors<Guid>.UserId(instance) = value;
                    return instance;
                });
            userId.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(3) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(3) && IdentityUserLoginUnsafeAccessors<Guid>.UserId(((IdentityUserLogin<Guid>)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : IdentityUserLoginUnsafeAccessors<Guid>.UserId(((IdentityUserLogin<Guid>)(entry.Entity))))),
                Guid (IInternalEntry entry) => IdentityUserLoginUnsafeAccessors<Guid>.UserId(((IdentityUserLogin<Guid>)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(userId, 3),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(userId, 2));
            userId.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: 2,
                storeGenerationIndex: 0);
            userId.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            userId.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(userId));
            userId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { loginProvider, providerKey });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { userId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var loginProvider = runtimeEntityType.FindProperty("LoginProvider");
            var providerKey = runtimeEntityType.FindProperty("ProviderKey");
            var providerDisplayName = runtimeEntityType.FindProperty("ProviderDisplayName");
            var userId = runtimeEntityType.FindProperty("UserId");
            var key = runtimeEntityType.FindKey(new[] { loginProvider, providerKey });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateCompositeFactory(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<IReadOnlyList<object>>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityUserLogin<Guid>)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, string, string, Guid>((source.GetCurrentValue<string>(loginProvider) == null ? null : ((ValueComparer<string>)(((IProperty)loginProvider).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(loginProvider))), (source.GetCurrentValue<string>(providerKey) == null ? null : ((ValueComparer<string>)(((IProperty)providerKey).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(providerKey))), (source.GetCurrentValue<string>(providerDisplayName) == null ? null : ((ValueComparer<string>)(((IProperty)providerDisplayName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(providerDisplayName))), ((ValueComparer<Guid>)(((IProperty)userId).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(userId)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)userId).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityUserLogin<Guid>)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, string, Guid>((source.GetCurrentValue<string>(loginProvider) == null ? null : ((ValueComparer<string>)(((IProperty)loginProvider).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(loginProvider))), (source.GetCurrentValue<string>(providerKey) == null ? null : ((ValueComparer<string>)(((IProperty)providerKey).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(providerKey))), ((ValueComparer<Guid>)(((IProperty)userId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(userId)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 4,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 4,
                shadowCount: 0,
                relationshipCount: 3,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "users");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AspNetUserLogins");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
