// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MonoSlice.Modules.Users.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class IdentityUserTokenEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>",
                typeof(IdentityUserToken<Guid>),
                baseEntityType,
                propertyCount: 4,
                foreignKeyCount: 1,
                keyCount: 1);

            var userId = runtimeEntityType.AddProperty(
                "UserId",
                typeof(Guid),
                propertyInfo: typeof(IdentityUserToken<Guid>).GetProperty("UserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserToken<Guid>).GetField("<UserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            userId.SetGetter(
                Guid (IdentityUserToken<Guid> instance) => IdentityUserTokenUnsafeAccessors<Guid>.UserId(instance),
                bool (IdentityUserToken<Guid> instance) => IdentityUserTokenUnsafeAccessors<Guid>.UserId(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            userId.SetSetter(
                IdentityUserToken<Guid> (IdentityUserToken<Guid> instance, Guid value) =>
                {
                    IdentityUserTokenUnsafeAccessors<Guid>.UserId(instance) = value;
                    return instance;
                });
            userId.SetMaterializationSetter(
                IdentityUserToken<Guid> (IdentityUserToken<Guid> instance, Guid value) =>
                {
                    IdentityUserTokenUnsafeAccessors<Guid>.UserId(instance) = value;
                    return instance;
                });
            userId.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && IdentityUserTokenUnsafeAccessors<Guid>.UserId(((IdentityUserToken<Guid>)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : IdentityUserTokenUnsafeAccessors<Guid>.UserId(((IdentityUserToken<Guid>)(entry.Entity))))),
                Guid (IInternalEntry entry) => IdentityUserTokenUnsafeAccessors<Guid>.UserId(((IdentityUserToken<Guid>)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(userId, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(userId, 0));
            userId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            userId.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            userId.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(userId));
            userId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var loginProvider = runtimeEntityType.AddProperty(
                "LoginProvider",
                typeof(string),
                propertyInfo: typeof(IdentityUserToken<Guid>).GetProperty("LoginProvider", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserToken<Guid>).GetField("<LoginProvider>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            loginProvider.SetGetter(
                string (IdentityUserToken<Guid> instance) => IdentityUserTokenUnsafeAccessors<Guid>.LoginProvider(instance),
                bool (IdentityUserToken<Guid> instance) => IdentityUserTokenUnsafeAccessors<Guid>.LoginProvider(instance) == null);
            loginProvider.SetSetter(
                IdentityUserToken<Guid> (IdentityUserToken<Guid> instance, string value) =>
                {
                    IdentityUserTokenUnsafeAccessors<Guid>.LoginProvider(instance) = value;
                    return instance;
                });
            loginProvider.SetMaterializationSetter(
                IdentityUserToken<Guid> (IdentityUserToken<Guid> instance, string value) =>
                {
                    IdentityUserTokenUnsafeAccessors<Guid>.LoginProvider(instance) = value;
                    return instance;
                });
            loginProvider.SetAccessors(
                string (IInternalEntry entry) => IdentityUserTokenUnsafeAccessors<Guid>.LoginProvider(((IdentityUserToken<Guid>)(entry.Entity))),
                string (IInternalEntry entry) => IdentityUserTokenUnsafeAccessors<Guid>.LoginProvider(((IdentityUserToken<Guid>)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(loginProvider, 1),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(loginProvider, 1));
            loginProvider.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            loginProvider.TypeMapping = StringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    dbType: System.Data.DbType.String));
            loginProvider.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(loginProvider));
            loginProvider.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(IdentityUserToken<Guid>).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserToken<Guid>).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            name.SetGetter(
                string (IdentityUserToken<Guid> instance) => IdentityUserTokenUnsafeAccessors<Guid>.Name(instance),
                bool (IdentityUserToken<Guid> instance) => IdentityUserTokenUnsafeAccessors<Guid>.Name(instance) == null);
            name.SetSetter(
                IdentityUserToken<Guid> (IdentityUserToken<Guid> instance, string value) =>
                {
                    IdentityUserTokenUnsafeAccessors<Guid>.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                IdentityUserToken<Guid> (IdentityUserToken<Guid> instance, string value) =>
                {
                    IdentityUserTokenUnsafeAccessors<Guid>.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => IdentityUserTokenUnsafeAccessors<Guid>.Name(((IdentityUserToken<Guid>)(entry.Entity))),
                string (IInternalEntry entry) => IdentityUserTokenUnsafeAccessors<Guid>.Name(((IdentityUserToken<Guid>)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 2),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(name, 2));
            name.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: 2,
                storeGenerationIndex: -1);
            name.TypeMapping = StringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    dbType: System.Data.DbType.String));
            name.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(name));
            name.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var value = runtimeEntityType.AddProperty(
                "Value",
                typeof(string),
                propertyInfo: typeof(IdentityUserToken<Guid>).GetProperty("Value", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserToken<Guid>).GetField("<Value>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            value.SetGetter(
                string (IdentityUserToken<Guid> instance) => IdentityUserTokenUnsafeAccessors<Guid>.Value(instance),
                bool (IdentityUserToken<Guid> instance) => IdentityUserTokenUnsafeAccessors<Guid>.Value(instance) == null);
            value.SetSetter(
                IdentityUserToken<Guid> (IdentityUserToken<Guid> instance, string value) =>
                {
                    IdentityUserTokenUnsafeAccessors<Guid>.Value(instance) = value;
                    return instance;
                });
            value.SetMaterializationSetter(
                IdentityUserToken<Guid> (IdentityUserToken<Guid> instance, string value) =>
                {
                    IdentityUserTokenUnsafeAccessors<Guid>.Value(instance) = value;
                    return instance;
                });
            value.SetAccessors(
                string (IInternalEntry entry) => IdentityUserTokenUnsafeAccessors<Guid>.Value(((IdentityUserToken<Guid>)(entry.Entity))),
                string (IInternalEntry entry) => IdentityUserTokenUnsafeAccessors<Guid>.Value(((IdentityUserToken<Guid>)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(value, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(value));
            value.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            value.TypeMapping = StringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    dbType: System.Data.DbType.String));
            value.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { userId, loginProvider, name });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var userId = runtimeEntityType.FindProperty("UserId");
            var loginProvider = runtimeEntityType.FindProperty("LoginProvider");
            var name = runtimeEntityType.FindProperty("Name");
            var value = runtimeEntityType.FindProperty("Value");
            var key = runtimeEntityType.FindKey(new[] { userId, loginProvider, name });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateCompositeFactory(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<IReadOnlyList<object>>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityUserToken<Guid>)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, string, string, string>(((ValueComparer<Guid>)(((IProperty)userId).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(userId)), (source.GetCurrentValue<string>(loginProvider) == null ? null : ((ValueComparer<string>)(((IProperty)loginProvider).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(loginProvider))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), (source.GetCurrentValue<string>(value) == null ? null : ((ValueComparer<string>)(((IProperty)value).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(value))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)userId).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityUserToken<Guid>)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, string, string>(((ValueComparer<Guid>)(((IProperty)userId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(userId)), (source.GetCurrentValue<string>(loginProvider) == null ? null : ((ValueComparer<string>)(((IProperty)loginProvider).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(loginProvider))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(name))))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 4,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 4,
                shadowCount: 0,
                relationshipCount: 3,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "users");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AspNetUserTokens");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
