// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MonoSlice.Modules.Users.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class IdentityUserClaimEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>",
                typeof(IdentityUserClaim<Guid>),
                baseEntityType,
                propertyCount: 4,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(IdentityUserClaim<Guid>).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserClaim<Guid>).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (IdentityUserClaim<Guid> instance) => IdentityUserClaimUnsafeAccessors<Guid>.Id(instance),
                bool (IdentityUserClaim<Guid> instance) => IdentityUserClaimUnsafeAccessors<Guid>.Id(instance) == 0);
            id.SetSetter(
                IdentityUserClaim<Guid> (IdentityUserClaim<Guid> instance, int value) =>
                {
                    IdentityUserClaimUnsafeAccessors<Guid>.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                IdentityUserClaim<Guid> (IdentityUserClaim<Guid> instance, int value) =>
                {
                    IdentityUserClaimUnsafeAccessors<Guid>.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && IdentityUserClaimUnsafeAccessors<Guid>.Id(((IdentityUserClaim<Guid>)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : IdentityUserClaimUnsafeAccessors<Guid>.Id(((IdentityUserClaim<Guid>)(entry.Entity))))),
                int (IInternalEntry entry) => IdentityUserClaimUnsafeAccessors<Guid>.Id(((IdentityUserClaim<Guid>)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            var claimType = runtimeEntityType.AddProperty(
                "ClaimType",
                typeof(string),
                propertyInfo: typeof(IdentityUserClaim<Guid>).GetProperty("ClaimType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserClaim<Guid>).GetField("<ClaimType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            claimType.SetGetter(
                string (IdentityUserClaim<Guid> instance) => IdentityUserClaimUnsafeAccessors<Guid>.ClaimType(instance),
                bool (IdentityUserClaim<Guid> instance) => IdentityUserClaimUnsafeAccessors<Guid>.ClaimType(instance) == null);
            claimType.SetSetter(
                IdentityUserClaim<Guid> (IdentityUserClaim<Guid> instance, string value) =>
                {
                    IdentityUserClaimUnsafeAccessors<Guid>.ClaimType(instance) = value;
                    return instance;
                });
            claimType.SetMaterializationSetter(
                IdentityUserClaim<Guid> (IdentityUserClaim<Guid> instance, string value) =>
                {
                    IdentityUserClaimUnsafeAccessors<Guid>.ClaimType(instance) = value;
                    return instance;
                });
            claimType.SetAccessors(
                string (IInternalEntry entry) => IdentityUserClaimUnsafeAccessors<Guid>.ClaimType(((IdentityUserClaim<Guid>)(entry.Entity))),
                string (IInternalEntry entry) => IdentityUserClaimUnsafeAccessors<Guid>.ClaimType(((IdentityUserClaim<Guid>)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(claimType, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(claimType));
            claimType.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            claimType.TypeMapping = StringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    dbType: System.Data.DbType.String));
            claimType.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var claimValue = runtimeEntityType.AddProperty(
                "ClaimValue",
                typeof(string),
                propertyInfo: typeof(IdentityUserClaim<Guid>).GetProperty("ClaimValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserClaim<Guid>).GetField("<ClaimValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            claimValue.SetGetter(
                string (IdentityUserClaim<Guid> instance) => IdentityUserClaimUnsafeAccessors<Guid>.ClaimValue(instance),
                bool (IdentityUserClaim<Guid> instance) => IdentityUserClaimUnsafeAccessors<Guid>.ClaimValue(instance) == null);
            claimValue.SetSetter(
                IdentityUserClaim<Guid> (IdentityUserClaim<Guid> instance, string value) =>
                {
                    IdentityUserClaimUnsafeAccessors<Guid>.ClaimValue(instance) = value;
                    return instance;
                });
            claimValue.SetMaterializationSetter(
                IdentityUserClaim<Guid> (IdentityUserClaim<Guid> instance, string value) =>
                {
                    IdentityUserClaimUnsafeAccessors<Guid>.ClaimValue(instance) = value;
                    return instance;
                });
            claimValue.SetAccessors(
                string (IInternalEntry entry) => IdentityUserClaimUnsafeAccessors<Guid>.ClaimValue(((IdentityUserClaim<Guid>)(entry.Entity))),
                string (IInternalEntry entry) => IdentityUserClaimUnsafeAccessors<Guid>.ClaimValue(((IdentityUserClaim<Guid>)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(claimValue, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(claimValue));
            claimValue.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            claimValue.TypeMapping = StringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    dbType: System.Data.DbType.String));
            claimValue.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var userId = runtimeEntityType.AddProperty(
                "UserId",
                typeof(Guid),
                propertyInfo: typeof(IdentityUserClaim<Guid>).GetProperty("UserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserClaim<Guid>).GetField("<UserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            userId.SetGetter(
                Guid (IdentityUserClaim<Guid> instance) => IdentityUserClaimUnsafeAccessors<Guid>.UserId(instance),
                bool (IdentityUserClaim<Guid> instance) => IdentityUserClaimUnsafeAccessors<Guid>.UserId(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            userId.SetSetter(
                IdentityUserClaim<Guid> (IdentityUserClaim<Guid> instance, Guid value) =>
                {
                    IdentityUserClaimUnsafeAccessors<Guid>.UserId(instance) = value;
                    return instance;
                });
            userId.SetMaterializationSetter(
                IdentityUserClaim<Guid> (IdentityUserClaim<Guid> instance, Guid value) =>
                {
                    IdentityUserClaimUnsafeAccessors<Guid>.UserId(instance) = value;
                    return instance;
                });
            userId.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(3) ? entry.ReadStoreGeneratedValue<Guid>(1) : (entry.FlaggedAsTemporary(3) && IdentityUserClaimUnsafeAccessors<Guid>.UserId(((IdentityUserClaim<Guid>)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(1) : IdentityUserClaimUnsafeAccessors<Guid>.UserId(((IdentityUserClaim<Guid>)(entry.Entity))))),
                Guid (IInternalEntry entry) => IdentityUserClaimUnsafeAccessors<Guid>.UserId(((IdentityUserClaim<Guid>)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(userId, 3),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(userId, 1));
            userId.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: 1);
            userId.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            userId.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(userId));
            userId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { userId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var claimType = runtimeEntityType.FindProperty("ClaimType");
            var claimValue = runtimeEntityType.FindProperty("ClaimValue");
            var userId = runtimeEntityType.FindProperty("UserId");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityUserClaim<Guid>)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, string, string, Guid>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), (source.GetCurrentValue<string>(claimType) == null ? null : ((ValueComparer<string>)(((IProperty)claimType).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(claimType))), (source.GetCurrentValue<string>(claimValue) == null ? null : ((ValueComparer<string>)(((IProperty)claimValue).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(claimValue))), ((ValueComparer<Guid>)(((IProperty)userId).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(userId)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int, Guid>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int)), ((ValueComparer<Guid>)(((IProperty)userId).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int, Guid>(default(int), default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityUserClaim<Guid>)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, Guid>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<Guid>)(((IProperty)userId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(userId)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 4,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 4,
                shadowCount: 0,
                relationshipCount: 2,
                storeGeneratedCount: 2));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "users");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AspNetUserClaims");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
