// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using MonoSlice.Modules.Users.Persistence;
using MonoSlice.Modules.Users.Persistence.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(UsersDbContext), typeof(UsersDbContextModel))]
