// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Update.Internal;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MonoSlice.Modules.Users.Persistence.CompiledModels
{
    public partial class UsersDbContextModel
    {
        private UsersDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("fdf259ba-4686-4377-b0e1-fe66d2b6a9d2"), entityTypeCount: 7)
        {
        }

        partial void Initialize()
        {
            var identityRoleClaim = IdentityRoleClaimEntityType.Create(this);
            var identityUserClaim = IdentityUserClaimEntityType.Create(this);
            var identityUserLogin = IdentityUserLoginEntityType.Create(this);
            var identityUserRole = IdentityUserRoleEntityType.Create(this);
            var identityUserToken = IdentityUserTokenEntityType.Create(this);
            var applicationRole = ApplicationRoleEntityType.Create(this);
            var applicationUser = ApplicationUserEntityType.Create(this);

            IdentityRoleClaimEntityType.CreateForeignKey1(identityRoleClaim, applicationRole);
            IdentityUserClaimEntityType.CreateForeignKey1(identityUserClaim, applicationUser);
            IdentityUserLoginEntityType.CreateForeignKey1(identityUserLogin, applicationUser);
            IdentityUserRoleEntityType.CreateForeignKey1(identityUserRole, applicationRole);
            IdentityUserRoleEntityType.CreateForeignKey2(identityUserRole, applicationUser);
            IdentityUserTokenEntityType.CreateForeignKey1(identityUserToken, applicationUser);

            IdentityRoleClaimEntityType.CreateAnnotations(identityRoleClaim);
            IdentityUserClaimEntityType.CreateAnnotations(identityUserClaim);
            IdentityUserLoginEntityType.CreateAnnotations(identityUserLogin);
            IdentityUserRoleEntityType.CreateAnnotations(identityUserRole);
            IdentityUserTokenEntityType.CreateAnnotations(identityUserToken);
            ApplicationRoleEntityType.CreateAnnotations(applicationRole);
            ApplicationUserEntityType.CreateAnnotations(applicationUser);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.11");
            AddAnnotation("Relational:DefaultSchema", "users");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var identityRoleClaim = FindEntityType("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            identityRoleClaim.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase = new TableBase("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", null, relationalModel);
            var claimTypeColumnBase = new ColumnBase<ColumnMappingBase>("ClaimType", "text", microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase.Columns.Add("ClaimType", claimTypeColumnBase);
            var claimValueColumnBase = new ColumnBase<ColumnMappingBase>("ClaimValue", "text", microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase.Columns.Add("ClaimValue", claimValueColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "integer", microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase.Columns.Add("Id", idColumnBase);
            var roleIdColumnBase = new ColumnBase<ColumnMappingBase>("RoleId", "uuid", microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase.Columns.Add("RoleId", roleIdColumnBase);
            relationalModel.DefaultTables.Add("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase);
            var microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidMappingBase = new TableMappingBase<ColumnMappingBase>(identityRoleClaim, microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase, null);
            microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidTableBase.AddTypeMapping(microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidMappingBase, false);
            defaultTableMappings.Add(microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, identityRoleClaim.FindProperty("Id")!, microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)claimTypeColumnBase, identityRoleClaim.FindProperty("ClaimType")!, microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)claimValueColumnBase, identityRoleClaim.FindProperty("ClaimValue")!, microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)roleIdColumnBase, identityRoleClaim.FindProperty("RoleId")!, microsoftAspNetCoreIdentityIdentityRoleClaimSystemGuidMappingBase);

            var tableMappings = new List<TableMapping>();
            identityRoleClaim.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var aspNetRoleClaimsTable = new Table("AspNetRoleClaims", "users", relationalModel);
            var idColumn = new Column("Id", "integer", aspNetRoleClaimsTable);
            aspNetRoleClaimsTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn);
            idColumn.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            var claimTypeColumn = new Column("ClaimType", "text", aspNetRoleClaimsTable)
            {
                IsNullable = true
            };
            aspNetRoleClaimsTable.Columns.Add("ClaimType", claimTypeColumn);
            claimTypeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(claimTypeColumn);
            var claimValueColumn = new Column("ClaimValue", "text", aspNetRoleClaimsTable)
            {
                IsNullable = true
            };
            aspNetRoleClaimsTable.Columns.Add("ClaimValue", claimValueColumn);
            claimValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(claimValueColumn);
            var roleIdColumn = new Column("RoleId", "uuid", aspNetRoleClaimsTable);
            aspNetRoleClaimsTable.Columns.Add("RoleId", roleIdColumn);
            roleIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(roleIdColumn);
            relationalModel.Tables.Add(("AspNetRoleClaims", "users"), aspNetRoleClaimsTable);
            var aspNetRoleClaimsTableMapping = new TableMapping(identityRoleClaim, aspNetRoleClaimsTable, null);
            aspNetRoleClaimsTable.AddTypeMapping(aspNetRoleClaimsTableMapping, false);
            tableMappings.Add(aspNetRoleClaimsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, identityRoleClaim.FindProperty("Id")!, aspNetRoleClaimsTableMapping);
            RelationalModel.CreateColumnMapping(claimTypeColumn, identityRoleClaim.FindProperty("ClaimType")!, aspNetRoleClaimsTableMapping);
            RelationalModel.CreateColumnMapping(claimValueColumn, identityRoleClaim.FindProperty("ClaimValue")!, aspNetRoleClaimsTableMapping);
            RelationalModel.CreateColumnMapping(roleIdColumn, identityRoleClaim.FindProperty("RoleId")!, aspNetRoleClaimsTableMapping);
            var pK_AspNetRoleClaims = new UniqueConstraint("PK_AspNetRoleClaims", aspNetRoleClaimsTable, new[] { idColumn });
            aspNetRoleClaimsTable.PrimaryKey = pK_AspNetRoleClaims;
            pK_AspNetRoleClaims.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_AspNetRoleClaims));
            var pK_AspNetRoleClaimsKey = RelationalModel.GetKey(this,
                "Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>",
                new[] { "Id" });
            pK_AspNetRoleClaims.MappedKeys.Add(pK_AspNetRoleClaimsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_AspNetRoleClaimsKey).Add(pK_AspNetRoleClaims);
            aspNetRoleClaimsTable.UniqueConstraints.Add("PK_AspNetRoleClaims", pK_AspNetRoleClaims);
            var iX_AspNetRoleClaims_RoleId = new TableIndex(
            "IX_AspNetRoleClaims_RoleId", aspNetRoleClaimsTable, new[] { roleIdColumn }, false);
            iX_AspNetRoleClaims_RoleId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<Guid>(iX_AspNetRoleClaims_RoleId));
            var iX_AspNetRoleClaims_RoleIdIx = RelationalModel.GetIndex(this,
                "Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>",
                new[] { "RoleId" });
            iX_AspNetRoleClaims_RoleId.MappedIndexes.Add(iX_AspNetRoleClaims_RoleIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_AspNetRoleClaims_RoleIdIx).Add(iX_AspNetRoleClaims_RoleId);
            aspNetRoleClaimsTable.Indexes.Add("IX_AspNetRoleClaims_RoleId", iX_AspNetRoleClaims_RoleId);

            var identityUserClaim = FindEntityType("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            identityUserClaim.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase = new TableBase("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", null, relationalModel);
            var claimTypeColumnBase0 = new ColumnBase<ColumnMappingBase>("ClaimType", "text", microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase.Columns.Add("ClaimType", claimTypeColumnBase0);
            var claimValueColumnBase0 = new ColumnBase<ColumnMappingBase>("ClaimValue", "text", microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase.Columns.Add("ClaimValue", claimValueColumnBase0);
            var idColumnBase0 = new ColumnBase<ColumnMappingBase>("Id", "integer", microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase.Columns.Add("Id", idColumnBase0);
            var userIdColumnBase = new ColumnBase<ColumnMappingBase>("UserId", "uuid", microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase.Columns.Add("UserId", userIdColumnBase);
            relationalModel.DefaultTables.Add("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase);
            var microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidMappingBase = new TableMappingBase<ColumnMappingBase>(identityUserClaim, microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase, null);
            microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidTableBase.AddTypeMapping(microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidMappingBase, false);
            defaultTableMappings0.Add(microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase0, identityUserClaim.FindProperty("Id")!, microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)claimTypeColumnBase0, identityUserClaim.FindProperty("ClaimType")!, microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)claimValueColumnBase0, identityUserClaim.FindProperty("ClaimValue")!, microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)userIdColumnBase, identityUserClaim.FindProperty("UserId")!, microsoftAspNetCoreIdentityIdentityUserClaimSystemGuidMappingBase);

            var tableMappings0 = new List<TableMapping>();
            identityUserClaim.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var aspNetUserClaimsTable = new Table("AspNetUserClaims", "users", relationalModel);
            var idColumn0 = new Column("Id", "integer", aspNetUserClaimsTable);
            aspNetUserClaimsTable.Columns.Add("Id", idColumn0);
            idColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn0);
            idColumn0.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            var claimTypeColumn0 = new Column("ClaimType", "text", aspNetUserClaimsTable)
            {
                IsNullable = true
            };
            aspNetUserClaimsTable.Columns.Add("ClaimType", claimTypeColumn0);
            claimTypeColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(claimTypeColumn0);
            var claimValueColumn0 = new Column("ClaimValue", "text", aspNetUserClaimsTable)
            {
                IsNullable = true
            };
            aspNetUserClaimsTable.Columns.Add("ClaimValue", claimValueColumn0);
            claimValueColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(claimValueColumn0);
            var userIdColumn = new Column("UserId", "uuid", aspNetUserClaimsTable);
            aspNetUserClaimsTable.Columns.Add("UserId", userIdColumn);
            userIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(userIdColumn);
            relationalModel.Tables.Add(("AspNetUserClaims", "users"), aspNetUserClaimsTable);
            var aspNetUserClaimsTableMapping = new TableMapping(identityUserClaim, aspNetUserClaimsTable, null);
            aspNetUserClaimsTable.AddTypeMapping(aspNetUserClaimsTableMapping, false);
            tableMappings0.Add(aspNetUserClaimsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn0, identityUserClaim.FindProperty("Id")!, aspNetUserClaimsTableMapping);
            RelationalModel.CreateColumnMapping(claimTypeColumn0, identityUserClaim.FindProperty("ClaimType")!, aspNetUserClaimsTableMapping);
            RelationalModel.CreateColumnMapping(claimValueColumn0, identityUserClaim.FindProperty("ClaimValue")!, aspNetUserClaimsTableMapping);
            RelationalModel.CreateColumnMapping(userIdColumn, identityUserClaim.FindProperty("UserId")!, aspNetUserClaimsTableMapping);
            var pK_AspNetUserClaims = new UniqueConstraint("PK_AspNetUserClaims", aspNetUserClaimsTable, new[] { idColumn0 });
            aspNetUserClaimsTable.PrimaryKey = pK_AspNetUserClaims;
            pK_AspNetUserClaims.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_AspNetUserClaims));
            var pK_AspNetUserClaimsKey = RelationalModel.GetKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>",
                new[] { "Id" });
            pK_AspNetUserClaims.MappedKeys.Add(pK_AspNetUserClaimsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_AspNetUserClaimsKey).Add(pK_AspNetUserClaims);
            aspNetUserClaimsTable.UniqueConstraints.Add("PK_AspNetUserClaims", pK_AspNetUserClaims);
            var iX_AspNetUserClaims_UserId = new TableIndex(
            "IX_AspNetUserClaims_UserId", aspNetUserClaimsTable, new[] { userIdColumn }, false);
            iX_AspNetUserClaims_UserId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<Guid>(iX_AspNetUserClaims_UserId));
            var iX_AspNetUserClaims_UserIdIx = RelationalModel.GetIndex(this,
                "Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>",
                new[] { "UserId" });
            iX_AspNetUserClaims_UserId.MappedIndexes.Add(iX_AspNetUserClaims_UserIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_AspNetUserClaims_UserIdIx).Add(iX_AspNetUserClaims_UserId);
            aspNetUserClaimsTable.Indexes.Add("IX_AspNetUserClaims_UserId", iX_AspNetUserClaims_UserId);

            var identityUserLogin = FindEntityType("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>")!;

            var defaultTableMappings1 = new List<TableMappingBase<ColumnMappingBase>>();
            identityUserLogin.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings1);
            var microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase = new TableBase("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", null, relationalModel);
            var loginProviderColumnBase = new ColumnBase<ColumnMappingBase>("LoginProvider", "text", microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase.Columns.Add("LoginProvider", loginProviderColumnBase);
            var providerDisplayNameColumnBase = new ColumnBase<ColumnMappingBase>("ProviderDisplayName", "text", microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase.Columns.Add("ProviderDisplayName", providerDisplayNameColumnBase);
            var providerKeyColumnBase = new ColumnBase<ColumnMappingBase>("ProviderKey", "text", microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase.Columns.Add("ProviderKey", providerKeyColumnBase);
            var userIdColumnBase0 = new ColumnBase<ColumnMappingBase>("UserId", "uuid", microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase.Columns.Add("UserId", userIdColumnBase0);
            relationalModel.DefaultTables.Add("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase);
            var microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidMappingBase = new TableMappingBase<ColumnMappingBase>(identityUserLogin, microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase, null);
            microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidTableBase.AddTypeMapping(microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidMappingBase, false);
            defaultTableMappings1.Add(microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)loginProviderColumnBase, identityUserLogin.FindProperty("LoginProvider")!, microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)providerKeyColumnBase, identityUserLogin.FindProperty("ProviderKey")!, microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)providerDisplayNameColumnBase, identityUserLogin.FindProperty("ProviderDisplayName")!, microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)userIdColumnBase0, identityUserLogin.FindProperty("UserId")!, microsoftAspNetCoreIdentityIdentityUserLoginSystemGuidMappingBase);

            var tableMappings1 = new List<TableMapping>();
            identityUserLogin.SetRuntimeAnnotation("Relational:TableMappings", tableMappings1);
            var aspNetUserLoginsTable = new Table("AspNetUserLogins", "users", relationalModel);
            var loginProviderColumn = new Column("LoginProvider", "text", aspNetUserLoginsTable);
            aspNetUserLoginsTable.Columns.Add("LoginProvider", loginProviderColumn);
            loginProviderColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(loginProviderColumn);
            var providerKeyColumn = new Column("ProviderKey", "text", aspNetUserLoginsTable);
            aspNetUserLoginsTable.Columns.Add("ProviderKey", providerKeyColumn);
            providerKeyColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(providerKeyColumn);
            var providerDisplayNameColumn = new Column("ProviderDisplayName", "text", aspNetUserLoginsTable)
            {
                IsNullable = true
            };
            aspNetUserLoginsTable.Columns.Add("ProviderDisplayName", providerDisplayNameColumn);
            providerDisplayNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(providerDisplayNameColumn);
            var userIdColumn0 = new Column("UserId", "uuid", aspNetUserLoginsTable);
            aspNetUserLoginsTable.Columns.Add("UserId", userIdColumn0);
            userIdColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(userIdColumn0);
            relationalModel.Tables.Add(("AspNetUserLogins", "users"), aspNetUserLoginsTable);
            var aspNetUserLoginsTableMapping = new TableMapping(identityUserLogin, aspNetUserLoginsTable, null);
            aspNetUserLoginsTable.AddTypeMapping(aspNetUserLoginsTableMapping, false);
            tableMappings1.Add(aspNetUserLoginsTableMapping);
            RelationalModel.CreateColumnMapping(loginProviderColumn, identityUserLogin.FindProperty("LoginProvider")!, aspNetUserLoginsTableMapping);
            RelationalModel.CreateColumnMapping(providerKeyColumn, identityUserLogin.FindProperty("ProviderKey")!, aspNetUserLoginsTableMapping);
            RelationalModel.CreateColumnMapping(providerDisplayNameColumn, identityUserLogin.FindProperty("ProviderDisplayName")!, aspNetUserLoginsTableMapping);
            RelationalModel.CreateColumnMapping(userIdColumn0, identityUserLogin.FindProperty("UserId")!, aspNetUserLoginsTableMapping);
            var pK_AspNetUserLogins = new UniqueConstraint("PK_AspNetUserLogins", aspNetUserLoginsTable, new[] { loginProviderColumn, providerKeyColumn });
            aspNetUserLoginsTable.PrimaryKey = pK_AspNetUserLogins;
            pK_AspNetUserLogins.SetRowKeyValueFactory(new CompositeRowKeyValueFactory(pK_AspNetUserLogins));
            var pK_AspNetUserLoginsKey = RelationalModel.GetKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>",
                new[] { "LoginProvider", "ProviderKey" });
            pK_AspNetUserLogins.MappedKeys.Add(pK_AspNetUserLoginsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_AspNetUserLoginsKey).Add(pK_AspNetUserLogins);
            aspNetUserLoginsTable.UniqueConstraints.Add("PK_AspNetUserLogins", pK_AspNetUserLogins);
            var iX_AspNetUserLogins_UserId = new TableIndex(
            "IX_AspNetUserLogins_UserId", aspNetUserLoginsTable, new[] { userIdColumn0 }, false);
            iX_AspNetUserLogins_UserId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<Guid>(iX_AspNetUserLogins_UserId));
            var iX_AspNetUserLogins_UserIdIx = RelationalModel.GetIndex(this,
                "Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>",
                new[] { "UserId" });
            iX_AspNetUserLogins_UserId.MappedIndexes.Add(iX_AspNetUserLogins_UserIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_AspNetUserLogins_UserIdIx).Add(iX_AspNetUserLogins_UserId);
            aspNetUserLoginsTable.Indexes.Add("IX_AspNetUserLogins_UserId", iX_AspNetUserLogins_UserId);

            var identityUserRole = FindEntityType("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>")!;

            var defaultTableMappings2 = new List<TableMappingBase<ColumnMappingBase>>();
            identityUserRole.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings2);
            var microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidTableBase = new TableBase("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", null, relationalModel);
            var roleIdColumnBase0 = new ColumnBase<ColumnMappingBase>("RoleId", "uuid", microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidTableBase.Columns.Add("RoleId", roleIdColumnBase0);
            var userIdColumnBase1 = new ColumnBase<ColumnMappingBase>("UserId", "uuid", microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidTableBase.Columns.Add("UserId", userIdColumnBase1);
            relationalModel.DefaultTables.Add("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidTableBase);
            var microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidMappingBase = new TableMappingBase<ColumnMappingBase>(identityUserRole, microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidTableBase, null);
            microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidTableBase.AddTypeMapping(microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidMappingBase, false);
            defaultTableMappings2.Add(microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)roleIdColumnBase0, identityUserRole.FindProperty("RoleId")!, microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)userIdColumnBase1, identityUserRole.FindProperty("UserId")!, microsoftAspNetCoreIdentityIdentityUserRoleSystemGuidMappingBase);

            var tableMappings2 = new List<TableMapping>();
            identityUserRole.SetRuntimeAnnotation("Relational:TableMappings", tableMappings2);
            var aspNetUserRolesTable = new Table("AspNetUserRoles", "users", relationalModel);
            var userIdColumn1 = new Column("UserId", "uuid", aspNetUserRolesTable);
            aspNetUserRolesTable.Columns.Add("UserId", userIdColumn1);
            userIdColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(userIdColumn1);
            var roleIdColumn0 = new Column("RoleId", "uuid", aspNetUserRolesTable);
            aspNetUserRolesTable.Columns.Add("RoleId", roleIdColumn0);
            roleIdColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(roleIdColumn0);
            relationalModel.Tables.Add(("AspNetUserRoles", "users"), aspNetUserRolesTable);
            var aspNetUserRolesTableMapping = new TableMapping(identityUserRole, aspNetUserRolesTable, null);
            aspNetUserRolesTable.AddTypeMapping(aspNetUserRolesTableMapping, false);
            tableMappings2.Add(aspNetUserRolesTableMapping);
            RelationalModel.CreateColumnMapping(roleIdColumn0, identityUserRole.FindProperty("RoleId")!, aspNetUserRolesTableMapping);
            RelationalModel.CreateColumnMapping(userIdColumn1, identityUserRole.FindProperty("UserId")!, aspNetUserRolesTableMapping);
            var pK_AspNetUserRoles = new UniqueConstraint("PK_AspNetUserRoles", aspNetUserRolesTable, new[] { userIdColumn1, roleIdColumn0 });
            aspNetUserRolesTable.PrimaryKey = pK_AspNetUserRoles;
            pK_AspNetUserRoles.SetRowKeyValueFactory(new CompositeRowKeyValueFactory(pK_AspNetUserRoles));
            var pK_AspNetUserRolesKey = RelationalModel.GetKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>",
                new[] { "UserId", "RoleId" });
            pK_AspNetUserRoles.MappedKeys.Add(pK_AspNetUserRolesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_AspNetUserRolesKey).Add(pK_AspNetUserRoles);
            aspNetUserRolesTable.UniqueConstraints.Add("PK_AspNetUserRoles", pK_AspNetUserRoles);
            var iX_AspNetUserRoles_RoleId = new TableIndex(
            "IX_AspNetUserRoles_RoleId", aspNetUserRolesTable, new[] { roleIdColumn0 }, false);
            iX_AspNetUserRoles_RoleId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<Guid>(iX_AspNetUserRoles_RoleId));
            var iX_AspNetUserRoles_RoleIdIx = RelationalModel.GetIndex(this,
                "Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>",
                new[] { "RoleId" });
            iX_AspNetUserRoles_RoleId.MappedIndexes.Add(iX_AspNetUserRoles_RoleIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_AspNetUserRoles_RoleIdIx).Add(iX_AspNetUserRoles_RoleId);
            aspNetUserRolesTable.Indexes.Add("IX_AspNetUserRoles_RoleId", iX_AspNetUserRoles_RoleId);

            var identityUserToken = FindEntityType("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>")!;

            var defaultTableMappings3 = new List<TableMappingBase<ColumnMappingBase>>();
            identityUserToken.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings3);
            var microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase = new TableBase("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", null, relationalModel);
            var loginProviderColumnBase0 = new ColumnBase<ColumnMappingBase>("LoginProvider", "text", microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase.Columns.Add("LoginProvider", loginProviderColumnBase0);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "text", microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase.Columns.Add("Name", nameColumnBase);
            var userIdColumnBase2 = new ColumnBase<ColumnMappingBase>("UserId", "uuid", microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase);
            microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase.Columns.Add("UserId", userIdColumnBase2);
            var valueColumnBase = new ColumnBase<ColumnMappingBase>("Value", "text", microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase.Columns.Add("Value", valueColumnBase);
            relationalModel.DefaultTables.Add("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase);
            var microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidMappingBase = new TableMappingBase<ColumnMappingBase>(identityUserToken, microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase, null);
            microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidTableBase.AddTypeMapping(microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidMappingBase, false);
            defaultTableMappings3.Add(microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)loginProviderColumnBase0, identityUserToken.FindProperty("LoginProvider")!, microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, identityUserToken.FindProperty("Name")!, microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)userIdColumnBase2, identityUserToken.FindProperty("UserId")!, microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)valueColumnBase, identityUserToken.FindProperty("Value")!, microsoftAspNetCoreIdentityIdentityUserTokenSystemGuidMappingBase);

            var tableMappings3 = new List<TableMapping>();
            identityUserToken.SetRuntimeAnnotation("Relational:TableMappings", tableMappings3);
            var aspNetUserTokensTable = new Table("AspNetUserTokens", "users", relationalModel);
            var userIdColumn2 = new Column("UserId", "uuid", aspNetUserTokensTable);
            aspNetUserTokensTable.Columns.Add("UserId", userIdColumn2);
            userIdColumn2.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(userIdColumn2);
            var loginProviderColumn0 = new Column("LoginProvider", "text", aspNetUserTokensTable);
            aspNetUserTokensTable.Columns.Add("LoginProvider", loginProviderColumn0);
            loginProviderColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(loginProviderColumn0);
            var nameColumn = new Column("Name", "text", aspNetUserTokensTable);
            aspNetUserTokensTable.Columns.Add("Name", nameColumn);
            nameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn);
            var valueColumn = new Column("Value", "text", aspNetUserTokensTable)
            {
                IsNullable = true
            };
            aspNetUserTokensTable.Columns.Add("Value", valueColumn);
            valueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(valueColumn);
            relationalModel.Tables.Add(("AspNetUserTokens", "users"), aspNetUserTokensTable);
            var aspNetUserTokensTableMapping = new TableMapping(identityUserToken, aspNetUserTokensTable, null);
            aspNetUserTokensTable.AddTypeMapping(aspNetUserTokensTableMapping, false);
            tableMappings3.Add(aspNetUserTokensTableMapping);
            RelationalModel.CreateColumnMapping(loginProviderColumn0, identityUserToken.FindProperty("LoginProvider")!, aspNetUserTokensTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, identityUserToken.FindProperty("Name")!, aspNetUserTokensTableMapping);
            RelationalModel.CreateColumnMapping(userIdColumn2, identityUserToken.FindProperty("UserId")!, aspNetUserTokensTableMapping);
            RelationalModel.CreateColumnMapping(valueColumn, identityUserToken.FindProperty("Value")!, aspNetUserTokensTableMapping);
            var pK_AspNetUserTokens = new UniqueConstraint("PK_AspNetUserTokens", aspNetUserTokensTable, new[] { userIdColumn2, loginProviderColumn0, nameColumn });
            aspNetUserTokensTable.PrimaryKey = pK_AspNetUserTokens;
            pK_AspNetUserTokens.SetRowKeyValueFactory(new CompositeRowKeyValueFactory(pK_AspNetUserTokens));
            var pK_AspNetUserTokensKey = RelationalModel.GetKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>",
                new[] { "UserId", "LoginProvider", "Name" });
            pK_AspNetUserTokens.MappedKeys.Add(pK_AspNetUserTokensKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_AspNetUserTokensKey).Add(pK_AspNetUserTokens);
            aspNetUserTokensTable.UniqueConstraints.Add("PK_AspNetUserTokens", pK_AspNetUserTokens);

            var applicationRole = FindEntityType("MonoSlice.Modules.Users.Domain.ApplicationRole")!;

            var defaultTableMappings4 = new List<TableMappingBase<ColumnMappingBase>>();
            applicationRole.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings4);
            var monoSliceModulesUsersDomainApplicationRoleTableBase = new TableBase("MonoSlice.Modules.Users.Domain.ApplicationRole", null, relationalModel);
            var concurrencyStampColumnBase = new ColumnBase<ColumnMappingBase>("ConcurrencyStamp", "text", monoSliceModulesUsersDomainApplicationRoleTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationRoleTableBase.Columns.Add("ConcurrencyStamp", concurrencyStampColumnBase);
            var descriptionColumnBase = new ColumnBase<ColumnMappingBase>("Description", "character varying(256)", monoSliceModulesUsersDomainApplicationRoleTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationRoleTableBase.Columns.Add("Description", descriptionColumnBase);
            var idColumnBase1 = new ColumnBase<ColumnMappingBase>("Id", "uuid", monoSliceModulesUsersDomainApplicationRoleTableBase);
            monoSliceModulesUsersDomainApplicationRoleTableBase.Columns.Add("Id", idColumnBase1);
            var nameColumnBase0 = new ColumnBase<ColumnMappingBase>("Name", "character varying(256)", monoSliceModulesUsersDomainApplicationRoleTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationRoleTableBase.Columns.Add("Name", nameColumnBase0);
            var normalizedNameColumnBase = new ColumnBase<ColumnMappingBase>("NormalizedName", "character varying(256)", monoSliceModulesUsersDomainApplicationRoleTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationRoleTableBase.Columns.Add("NormalizedName", normalizedNameColumnBase);
            relationalModel.DefaultTables.Add("MonoSlice.Modules.Users.Domain.ApplicationRole", monoSliceModulesUsersDomainApplicationRoleTableBase);
            var monoSliceModulesUsersDomainApplicationRoleMappingBase = new TableMappingBase<ColumnMappingBase>(applicationRole, monoSliceModulesUsersDomainApplicationRoleTableBase, null);
            monoSliceModulesUsersDomainApplicationRoleTableBase.AddTypeMapping(monoSliceModulesUsersDomainApplicationRoleMappingBase, false);
            defaultTableMappings4.Add(monoSliceModulesUsersDomainApplicationRoleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase1, applicationRole.FindProperty("Id")!, monoSliceModulesUsersDomainApplicationRoleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)concurrencyStampColumnBase, applicationRole.FindProperty("ConcurrencyStamp")!, monoSliceModulesUsersDomainApplicationRoleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)descriptionColumnBase, applicationRole.FindProperty("Description")!, monoSliceModulesUsersDomainApplicationRoleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase0, applicationRole.FindProperty("Name")!, monoSliceModulesUsersDomainApplicationRoleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)normalizedNameColumnBase, applicationRole.FindProperty("NormalizedName")!, monoSliceModulesUsersDomainApplicationRoleMappingBase);

            var tableMappings4 = new List<TableMapping>();
            applicationRole.SetRuntimeAnnotation("Relational:TableMappings", tableMappings4);
            var rolesTable = new Table("Roles", "users", relationalModel);
            var idColumn1 = new Column("Id", "uuid", rolesTable);
            rolesTable.Columns.Add("Id", idColumn1);
            idColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn1);
            var concurrencyStampColumn = new Column("ConcurrencyStamp", "text", rolesTable)
            {
                IsNullable = true
            };
            rolesTable.Columns.Add("ConcurrencyStamp", concurrencyStampColumn);
            concurrencyStampColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(concurrencyStampColumn);
            var descriptionColumn = new Column("Description", "character varying(256)", rolesTable)
            {
                IsNullable = true
            };
            rolesTable.Columns.Add("Description", descriptionColumn);
            descriptionColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(descriptionColumn);
            var nameColumn0 = new Column("Name", "character varying(256)", rolesTable)
            {
                IsNullable = true
            };
            rolesTable.Columns.Add("Name", nameColumn0);
            nameColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn0);
            var normalizedNameColumn = new Column("NormalizedName", "character varying(256)", rolesTable)
            {
                IsNullable = true
            };
            rolesTable.Columns.Add("NormalizedName", normalizedNameColumn);
            normalizedNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(normalizedNameColumn);
            relationalModel.Tables.Add(("Roles", "users"), rolesTable);
            var rolesTableMapping = new TableMapping(applicationRole, rolesTable, null);
            rolesTable.AddTypeMapping(rolesTableMapping, false);
            tableMappings4.Add(rolesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn1, applicationRole.FindProperty("Id")!, rolesTableMapping);
            RelationalModel.CreateColumnMapping(concurrencyStampColumn, applicationRole.FindProperty("ConcurrencyStamp")!, rolesTableMapping);
            RelationalModel.CreateColumnMapping(descriptionColumn, applicationRole.FindProperty("Description")!, rolesTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn0, applicationRole.FindProperty("Name")!, rolesTableMapping);
            RelationalModel.CreateColumnMapping(normalizedNameColumn, applicationRole.FindProperty("NormalizedName")!, rolesTableMapping);
            var pK_Roles = new UniqueConstraint("PK_Roles", rolesTable, new[] { idColumn1 });
            rolesTable.PrimaryKey = pK_Roles;
            pK_Roles.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_Roles));
            var pK_RolesKey = RelationalModel.GetKey(this,
                "MonoSlice.Modules.Users.Domain.ApplicationRole",
                new[] { "Id" });
            pK_Roles.MappedKeys.Add(pK_RolesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_RolesKey).Add(pK_Roles);
            rolesTable.UniqueConstraints.Add("PK_Roles", pK_Roles);
            var roleNameIndex = new TableIndex(
            "RoleNameIndex", rolesTable, new[] { normalizedNameColumn }, true);
            roleNameIndex.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(roleNameIndex));
            var roleNameIndexIx = RelationalModel.GetIndex(this,
                "MonoSlice.Modules.Users.Domain.ApplicationRole",
                new[] { "NormalizedName" });
            roleNameIndex.MappedIndexes.Add(roleNameIndexIx);
            RelationalModel.GetOrCreateTableIndexes(roleNameIndexIx).Add(roleNameIndex);
            rolesTable.Indexes.Add("RoleNameIndex", roleNameIndex);

            var applicationUser = FindEntityType("MonoSlice.Modules.Users.Domain.ApplicationUser")!;

            var defaultTableMappings5 = new List<TableMappingBase<ColumnMappingBase>>();
            applicationUser.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings5);
            var monoSliceModulesUsersDomainApplicationUserTableBase = new TableBase("MonoSlice.Modules.Users.Domain.ApplicationUser", null, relationalModel);
            var accessFailedCountColumnBase = new ColumnBase<ColumnMappingBase>("AccessFailedCount", "integer", monoSliceModulesUsersDomainApplicationUserTableBase);
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("AccessFailedCount", accessFailedCountColumnBase);
            var concurrencyStampColumnBase0 = new ColumnBase<ColumnMappingBase>("ConcurrencyStamp", "text", monoSliceModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("ConcurrencyStamp", concurrencyStampColumnBase0);
            var createdAtColumnBase = new ColumnBase<ColumnMappingBase>("CreatedAt", "timestamp with time zone", monoSliceModulesUsersDomainApplicationUserTableBase);
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("CreatedAt", createdAtColumnBase);
            var emailColumnBase = new ColumnBase<ColumnMappingBase>("Email", "character varying(256)", monoSliceModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("Email", emailColumnBase);
            var emailConfirmedColumnBase = new ColumnBase<ColumnMappingBase>("EmailConfirmed", "boolean", monoSliceModulesUsersDomainApplicationUserTableBase);
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("EmailConfirmed", emailConfirmedColumnBase);
            var firstNameColumnBase = new ColumnBase<ColumnMappingBase>("FirstName", "character varying(100)", monoSliceModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("FirstName", firstNameColumnBase);
            var idColumnBase2 = new ColumnBase<ColumnMappingBase>("Id", "uuid", monoSliceModulesUsersDomainApplicationUserTableBase);
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("Id", idColumnBase2);
            var lastNameColumnBase = new ColumnBase<ColumnMappingBase>("LastName", "character varying(100)", monoSliceModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("LastName", lastNameColumnBase);
            var lockoutEnabledColumnBase = new ColumnBase<ColumnMappingBase>("LockoutEnabled", "boolean", monoSliceModulesUsersDomainApplicationUserTableBase);
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("LockoutEnabled", lockoutEnabledColumnBase);
            var lockoutEndColumnBase = new ColumnBase<ColumnMappingBase>("LockoutEnd", "timestamp with time zone", monoSliceModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("LockoutEnd", lockoutEndColumnBase);
            var normalizedEmailColumnBase = new ColumnBase<ColumnMappingBase>("NormalizedEmail", "character varying(256)", monoSliceModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("NormalizedEmail", normalizedEmailColumnBase);
            var normalizedUserNameColumnBase = new ColumnBase<ColumnMappingBase>("NormalizedUserName", "character varying(256)", monoSliceModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("NormalizedUserName", normalizedUserNameColumnBase);
            var passwordHashColumnBase = new ColumnBase<ColumnMappingBase>("PasswordHash", "text", monoSliceModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("PasswordHash", passwordHashColumnBase);
            var phoneNumberColumnBase = new ColumnBase<ColumnMappingBase>("PhoneNumber", "text", monoSliceModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("PhoneNumber", phoneNumberColumnBase);
            var phoneNumberConfirmedColumnBase = new ColumnBase<ColumnMappingBase>("PhoneNumberConfirmed", "boolean", monoSliceModulesUsersDomainApplicationUserTableBase);
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("PhoneNumberConfirmed", phoneNumberConfirmedColumnBase);
            var refreshTokenColumnBase = new ColumnBase<ColumnMappingBase>("RefreshToken", "character varying(256)", monoSliceModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("RefreshToken", refreshTokenColumnBase);
            var refreshTokenExpiryTimeColumnBase = new ColumnBase<ColumnMappingBase>("RefreshTokenExpiryTime", "timestamp with time zone", monoSliceModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("RefreshTokenExpiryTime", refreshTokenExpiryTimeColumnBase);
            var securityStampColumnBase = new ColumnBase<ColumnMappingBase>("SecurityStamp", "text", monoSliceModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("SecurityStamp", securityStampColumnBase);
            var twoFactorEnabledColumnBase = new ColumnBase<ColumnMappingBase>("TwoFactorEnabled", "boolean", monoSliceModulesUsersDomainApplicationUserTableBase);
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("TwoFactorEnabled", twoFactorEnabledColumnBase);
            var updatedAtColumnBase = new ColumnBase<ColumnMappingBase>("UpdatedAt", "timestamp with time zone", monoSliceModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("UpdatedAt", updatedAtColumnBase);
            var userNameColumnBase = new ColumnBase<ColumnMappingBase>("UserName", "character varying(256)", monoSliceModulesUsersDomainApplicationUserTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesUsersDomainApplicationUserTableBase.Columns.Add("UserName", userNameColumnBase);
            relationalModel.DefaultTables.Add("MonoSlice.Modules.Users.Domain.ApplicationUser", monoSliceModulesUsersDomainApplicationUserTableBase);
            var monoSliceModulesUsersDomainApplicationUserMappingBase = new TableMappingBase<ColumnMappingBase>(applicationUser, monoSliceModulesUsersDomainApplicationUserTableBase, null);
            monoSliceModulesUsersDomainApplicationUserTableBase.AddTypeMapping(monoSliceModulesUsersDomainApplicationUserMappingBase, false);
            defaultTableMappings5.Add(monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase2, applicationUser.FindProperty("Id")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)accessFailedCountColumnBase, applicationUser.FindProperty("AccessFailedCount")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)concurrencyStampColumnBase0, applicationUser.FindProperty("ConcurrencyStamp")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase, applicationUser.FindProperty("CreatedAt")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)emailColumnBase, applicationUser.FindProperty("Email")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)emailConfirmedColumnBase, applicationUser.FindProperty("EmailConfirmed")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)firstNameColumnBase, applicationUser.FindProperty("FirstName")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lastNameColumnBase, applicationUser.FindProperty("LastName")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lockoutEnabledColumnBase, applicationUser.FindProperty("LockoutEnabled")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lockoutEndColumnBase, applicationUser.FindProperty("LockoutEnd")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)normalizedEmailColumnBase, applicationUser.FindProperty("NormalizedEmail")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)normalizedUserNameColumnBase, applicationUser.FindProperty("NormalizedUserName")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)passwordHashColumnBase, applicationUser.FindProperty("PasswordHash")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)phoneNumberColumnBase, applicationUser.FindProperty("PhoneNumber")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)phoneNumberConfirmedColumnBase, applicationUser.FindProperty("PhoneNumberConfirmed")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)refreshTokenColumnBase, applicationUser.FindProperty("RefreshToken")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)refreshTokenExpiryTimeColumnBase, applicationUser.FindProperty("RefreshTokenExpiryTime")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)securityStampColumnBase, applicationUser.FindProperty("SecurityStamp")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)twoFactorEnabledColumnBase, applicationUser.FindProperty("TwoFactorEnabled")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)updatedAtColumnBase, applicationUser.FindProperty("UpdatedAt")!, monoSliceModulesUsersDomainApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)userNameColumnBase, applicationUser.FindProperty("UserName")!, monoSliceModulesUsersDomainApplicationUserMappingBase);

            var tableMappings5 = new List<TableMapping>();
            applicationUser.SetRuntimeAnnotation("Relational:TableMappings", tableMappings5);
            var usersTable = new Table("Users", "users", relationalModel);
            var idColumn2 = new Column("Id", "uuid", usersTable);
            usersTable.Columns.Add("Id", idColumn2);
            idColumn2.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn2);
            var accessFailedCountColumn = new Column("AccessFailedCount", "integer", usersTable);
            usersTable.Columns.Add("AccessFailedCount", accessFailedCountColumn);
            accessFailedCountColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(accessFailedCountColumn);
            var concurrencyStampColumn0 = new Column("ConcurrencyStamp", "text", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("ConcurrencyStamp", concurrencyStampColumn0);
            concurrencyStampColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(concurrencyStampColumn0);
            var createdAtColumn = new Column("CreatedAt", "timestamp with time zone", usersTable);
            usersTable.Columns.Add("CreatedAt", createdAtColumn);
            createdAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(createdAtColumn);
            var emailColumn = new Column("Email", "character varying(256)", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("Email", emailColumn);
            emailColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(emailColumn);
            var emailConfirmedColumn = new Column("EmailConfirmed", "boolean", usersTable);
            usersTable.Columns.Add("EmailConfirmed", emailConfirmedColumn);
            emailConfirmedColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(emailConfirmedColumn);
            var firstNameColumn = new Column("FirstName", "character varying(100)", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("FirstName", firstNameColumn);
            firstNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(firstNameColumn);
            var lastNameColumn = new Column("LastName", "character varying(100)", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("LastName", lastNameColumn);
            lastNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(lastNameColumn);
            var lockoutEnabledColumn = new Column("LockoutEnabled", "boolean", usersTable);
            usersTable.Columns.Add("LockoutEnabled", lockoutEnabledColumn);
            lockoutEnabledColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(lockoutEnabledColumn);
            var lockoutEndColumn = new Column("LockoutEnd", "timestamp with time zone", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("LockoutEnd", lockoutEndColumn);
            lockoutEndColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTimeOffset>(lockoutEndColumn);
            var normalizedEmailColumn = new Column("NormalizedEmail", "character varying(256)", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("NormalizedEmail", normalizedEmailColumn);
            normalizedEmailColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(normalizedEmailColumn);
            var normalizedUserNameColumn = new Column("NormalizedUserName", "character varying(256)", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("NormalizedUserName", normalizedUserNameColumn);
            normalizedUserNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(normalizedUserNameColumn);
            var passwordHashColumn = new Column("PasswordHash", "text", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("PasswordHash", passwordHashColumn);
            passwordHashColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(passwordHashColumn);
            var phoneNumberColumn = new Column("PhoneNumber", "text", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("PhoneNumber", phoneNumberColumn);
            phoneNumberColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(phoneNumberColumn);
            var phoneNumberConfirmedColumn = new Column("PhoneNumberConfirmed", "boolean", usersTable);
            usersTable.Columns.Add("PhoneNumberConfirmed", phoneNumberConfirmedColumn);
            phoneNumberConfirmedColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(phoneNumberConfirmedColumn);
            var refreshTokenColumn = new Column("RefreshToken", "character varying(256)", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("RefreshToken", refreshTokenColumn);
            refreshTokenColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(refreshTokenColumn);
            var refreshTokenExpiryTimeColumn = new Column("RefreshTokenExpiryTime", "timestamp with time zone", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("RefreshTokenExpiryTime", refreshTokenExpiryTimeColumn);
            refreshTokenExpiryTimeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(refreshTokenExpiryTimeColumn);
            var securityStampColumn = new Column("SecurityStamp", "text", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("SecurityStamp", securityStampColumn);
            securityStampColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(securityStampColumn);
            var twoFactorEnabledColumn = new Column("TwoFactorEnabled", "boolean", usersTable);
            usersTable.Columns.Add("TwoFactorEnabled", twoFactorEnabledColumn);
            twoFactorEnabledColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(twoFactorEnabledColumn);
            var updatedAtColumn = new Column("UpdatedAt", "timestamp with time zone", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("UpdatedAt", updatedAtColumn);
            updatedAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(updatedAtColumn);
            var userNameColumn = new Column("UserName", "character varying(256)", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("UserName", userNameColumn);
            userNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(userNameColumn);
            relationalModel.Tables.Add(("Users", "users"), usersTable);
            var usersTableMapping = new TableMapping(applicationUser, usersTable, null);
            usersTable.AddTypeMapping(usersTableMapping, false);
            tableMappings5.Add(usersTableMapping);
            RelationalModel.CreateColumnMapping(idColumn2, applicationUser.FindProperty("Id")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(accessFailedCountColumn, applicationUser.FindProperty("AccessFailedCount")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(concurrencyStampColumn0, applicationUser.FindProperty("ConcurrencyStamp")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn, applicationUser.FindProperty("CreatedAt")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(emailColumn, applicationUser.FindProperty("Email")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(emailConfirmedColumn, applicationUser.FindProperty("EmailConfirmed")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(firstNameColumn, applicationUser.FindProperty("FirstName")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(lastNameColumn, applicationUser.FindProperty("LastName")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(lockoutEnabledColumn, applicationUser.FindProperty("LockoutEnabled")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(lockoutEndColumn, applicationUser.FindProperty("LockoutEnd")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(normalizedEmailColumn, applicationUser.FindProperty("NormalizedEmail")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(normalizedUserNameColumn, applicationUser.FindProperty("NormalizedUserName")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(passwordHashColumn, applicationUser.FindProperty("PasswordHash")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(phoneNumberColumn, applicationUser.FindProperty("PhoneNumber")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(phoneNumberConfirmedColumn, applicationUser.FindProperty("PhoneNumberConfirmed")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(refreshTokenColumn, applicationUser.FindProperty("RefreshToken")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(refreshTokenExpiryTimeColumn, applicationUser.FindProperty("RefreshTokenExpiryTime")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(securityStampColumn, applicationUser.FindProperty("SecurityStamp")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(twoFactorEnabledColumn, applicationUser.FindProperty("TwoFactorEnabled")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(updatedAtColumn, applicationUser.FindProperty("UpdatedAt")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(userNameColumn, applicationUser.FindProperty("UserName")!, usersTableMapping);
            var pK_Users = new UniqueConstraint("PK_Users", usersTable, new[] { idColumn2 });
            usersTable.PrimaryKey = pK_Users;
            pK_Users.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_Users));
            var pK_UsersKey = RelationalModel.GetKey(this,
                "MonoSlice.Modules.Users.Domain.ApplicationUser",
                new[] { "Id" });
            pK_Users.MappedKeys.Add(pK_UsersKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_UsersKey).Add(pK_Users);
            usersTable.UniqueConstraints.Add("PK_Users", pK_Users);
            var emailIndex = new TableIndex(
            "EmailIndex", usersTable, new[] { normalizedEmailColumn }, false);
            emailIndex.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(emailIndex));
            var emailIndexIx = RelationalModel.GetIndex(this,
                "MonoSlice.Modules.Users.Domain.ApplicationUser",
                new[] { "NormalizedEmail" });
            emailIndex.MappedIndexes.Add(emailIndexIx);
            RelationalModel.GetOrCreateTableIndexes(emailIndexIx).Add(emailIndex);
            usersTable.Indexes.Add("EmailIndex", emailIndex);
            var userNameIndex = new TableIndex(
            "UserNameIndex", usersTable, new[] { normalizedUserNameColumn }, true);
            userNameIndex.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(userNameIndex));
            var userNameIndexIx = RelationalModel.GetIndex(this,
                "MonoSlice.Modules.Users.Domain.ApplicationUser",
                new[] { "NormalizedUserName" });
            userNameIndex.MappedIndexes.Add(userNameIndexIx);
            RelationalModel.GetOrCreateTableIndexes(userNameIndexIx).Add(userNameIndex);
            usersTable.Indexes.Add("UserNameIndex", userNameIndex);
            var fK_AspNetRoleClaims_Roles_RoleId = new ForeignKeyConstraint(
                "FK_AspNetRoleClaims_Roles_RoleId", aspNetRoleClaimsTable, rolesTable,
                new[] { roleIdColumn },
                rolesTable.FindUniqueConstraint("PK_Roles")!, ReferentialAction.Cascade);
            fK_AspNetRoleClaims_Roles_RoleId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid, Guid>(fK_AspNetRoleClaims_Roles_RoleId));
            var fK_AspNetRoleClaims_Roles_RoleIdFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>",
                new[] { "RoleId" },
                "MonoSlice.Modules.Users.Domain.ApplicationRole",
                new[] { "Id" });
            fK_AspNetRoleClaims_Roles_RoleId.MappedForeignKeys.Add(fK_AspNetRoleClaims_Roles_RoleIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_AspNetRoleClaims_Roles_RoleIdFk).Add(fK_AspNetRoleClaims_Roles_RoleId);
            aspNetRoleClaimsTable.ForeignKeyConstraints.Add(fK_AspNetRoleClaims_Roles_RoleId);
            rolesTable.ReferencingForeignKeyConstraints.Add(fK_AspNetRoleClaims_Roles_RoleId);
            var fK_AspNetUserClaims_Users_UserId = new ForeignKeyConstraint(
                "FK_AspNetUserClaims_Users_UserId", aspNetUserClaimsTable, usersTable,
                new[] { userIdColumn },
                usersTable.FindUniqueConstraint("PK_Users")!, ReferentialAction.Cascade);
            fK_AspNetUserClaims_Users_UserId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid, Guid>(fK_AspNetUserClaims_Users_UserId));
            var fK_AspNetUserClaims_Users_UserIdFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>",
                new[] { "UserId" },
                "MonoSlice.Modules.Users.Domain.ApplicationUser",
                new[] { "Id" });
            fK_AspNetUserClaims_Users_UserId.MappedForeignKeys.Add(fK_AspNetUserClaims_Users_UserIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_AspNetUserClaims_Users_UserIdFk).Add(fK_AspNetUserClaims_Users_UserId);
            aspNetUserClaimsTable.ForeignKeyConstraints.Add(fK_AspNetUserClaims_Users_UserId);
            usersTable.ReferencingForeignKeyConstraints.Add(fK_AspNetUserClaims_Users_UserId);
            var fK_AspNetUserLogins_Users_UserId = new ForeignKeyConstraint(
                "FK_AspNetUserLogins_Users_UserId", aspNetUserLoginsTable, usersTable,
                new[] { userIdColumn0 },
                usersTable.FindUniqueConstraint("PK_Users")!, ReferentialAction.Cascade);
            fK_AspNetUserLogins_Users_UserId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid, Guid>(fK_AspNetUserLogins_Users_UserId));
            var fK_AspNetUserLogins_Users_UserIdFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>",
                new[] { "UserId" },
                "MonoSlice.Modules.Users.Domain.ApplicationUser",
                new[] { "Id" });
            fK_AspNetUserLogins_Users_UserId.MappedForeignKeys.Add(fK_AspNetUserLogins_Users_UserIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_AspNetUserLogins_Users_UserIdFk).Add(fK_AspNetUserLogins_Users_UserId);
            aspNetUserLoginsTable.ForeignKeyConstraints.Add(fK_AspNetUserLogins_Users_UserId);
            usersTable.ReferencingForeignKeyConstraints.Add(fK_AspNetUserLogins_Users_UserId);
            var fK_AspNetUserRoles_Roles_RoleId = new ForeignKeyConstraint(
                "FK_AspNetUserRoles_Roles_RoleId", aspNetUserRolesTable, rolesTable,
                new[] { roleIdColumn0 },
                rolesTable.FindUniqueConstraint("PK_Roles")!, ReferentialAction.Cascade);
            fK_AspNetUserRoles_Roles_RoleId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid, Guid>(fK_AspNetUserRoles_Roles_RoleId));
            var fK_AspNetUserRoles_Roles_RoleIdFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>",
                new[] { "RoleId" },
                "MonoSlice.Modules.Users.Domain.ApplicationRole",
                new[] { "Id" });
            fK_AspNetUserRoles_Roles_RoleId.MappedForeignKeys.Add(fK_AspNetUserRoles_Roles_RoleIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_AspNetUserRoles_Roles_RoleIdFk).Add(fK_AspNetUserRoles_Roles_RoleId);
            aspNetUserRolesTable.ForeignKeyConstraints.Add(fK_AspNetUserRoles_Roles_RoleId);
            rolesTable.ReferencingForeignKeyConstraints.Add(fK_AspNetUserRoles_Roles_RoleId);
            var fK_AspNetUserRoles_Users_UserId = new ForeignKeyConstraint(
                "FK_AspNetUserRoles_Users_UserId", aspNetUserRolesTable, usersTable,
                new[] { userIdColumn1 },
                usersTable.FindUniqueConstraint("PK_Users")!, ReferentialAction.Cascade);
            fK_AspNetUserRoles_Users_UserId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid, Guid>(fK_AspNetUserRoles_Users_UserId));
            var fK_AspNetUserRoles_Users_UserIdFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>",
                new[] { "UserId" },
                "MonoSlice.Modules.Users.Domain.ApplicationUser",
                new[] { "Id" });
            fK_AspNetUserRoles_Users_UserId.MappedForeignKeys.Add(fK_AspNetUserRoles_Users_UserIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_AspNetUserRoles_Users_UserIdFk).Add(fK_AspNetUserRoles_Users_UserId);
            aspNetUserRolesTable.ForeignKeyConstraints.Add(fK_AspNetUserRoles_Users_UserId);
            usersTable.ReferencingForeignKeyConstraints.Add(fK_AspNetUserRoles_Users_UserId);
            var fK_AspNetUserTokens_Users_UserId = new ForeignKeyConstraint(
                "FK_AspNetUserTokens_Users_UserId", aspNetUserTokensTable, usersTable,
                new[] { userIdColumn2 },
                usersTable.FindUniqueConstraint("PK_Users")!, ReferentialAction.Cascade);
            fK_AspNetUserTokens_Users_UserId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid, Guid>(fK_AspNetUserTokens_Users_UserId));
            var fK_AspNetUserTokens_Users_UserIdFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>",
                new[] { "UserId" },
                "MonoSlice.Modules.Users.Domain.ApplicationUser",
                new[] { "Id" });
            fK_AspNetUserTokens_Users_UserId.MappedForeignKeys.Add(fK_AspNetUserTokens_Users_UserIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_AspNetUserTokens_Users_UserIdFk).Add(fK_AspNetUserTokens_Users_UserId);
            aspNetUserTokensTable.ForeignKeyConstraints.Add(fK_AspNetUserTokens_Users_UserId);
            usersTable.ReferencingForeignKeyConstraints.Add(fK_AspNetUserTokens_Users_UserId);
            return relationalModel.MakeReadOnly();
        }
    }
}
