// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using MonoSlice.Modules.Catalog.Persistence;
using MonoSlice.Modules.Catalog.Persistence.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(CatalogDbContext), typeof(CatalogDbContextModel))]
