// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MonoSlice.Modules.Catalog.Persistence.CompiledModels
{
    public partial class CatalogDbContextModel
    {
        private CatalogDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("3b0f5c91-1038-49d5-890d-78ca015fe4a8"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var product = ProductEntityType.Create(this);

            ProductEntityType.CreateAnnotations(product);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.11");
            AddAnnotation("Relational:DefaultSchema", "catalog");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var product = FindEntityType("MonoSlice.Modules.Catalog.Domain.Product")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            product.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var monoSliceModulesCatalogDomainProductTableBase = new TableBase("MonoSlice.Modules.Catalog.Domain.Product", null, relationalModel);
            var createdAtColumnBase = new ColumnBase<ColumnMappingBase>("CreatedAt", "timestamp with time zone", monoSliceModulesCatalogDomainProductTableBase);
            monoSliceModulesCatalogDomainProductTableBase.Columns.Add("CreatedAt", createdAtColumnBase);
            var descriptionColumnBase = new ColumnBase<ColumnMappingBase>("Description", "character varying(1000)", monoSliceModulesCatalogDomainProductTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesCatalogDomainProductTableBase.Columns.Add("Description", descriptionColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "uuid", monoSliceModulesCatalogDomainProductTableBase);
            monoSliceModulesCatalogDomainProductTableBase.Columns.Add("Id", idColumnBase);
            var isActiveColumnBase = new ColumnBase<ColumnMappingBase>("IsActive", "boolean", monoSliceModulesCatalogDomainProductTableBase);
            monoSliceModulesCatalogDomainProductTableBase.Columns.Add("IsActive", isActiveColumnBase);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "character varying(200)", monoSliceModulesCatalogDomainProductTableBase);
            monoSliceModulesCatalogDomainProductTableBase.Columns.Add("Name", nameColumnBase);
            var priceColumnBase = new ColumnBase<ColumnMappingBase>("Price", "numeric(18,2)", monoSliceModulesCatalogDomainProductTableBase);
            monoSliceModulesCatalogDomainProductTableBase.Columns.Add("Price", priceColumnBase);
            var skuColumnBase = new ColumnBase<ColumnMappingBase>("Sku", "character varying(50)", monoSliceModulesCatalogDomainProductTableBase);
            monoSliceModulesCatalogDomainProductTableBase.Columns.Add("Sku", skuColumnBase);
            var stockQuantityColumnBase = new ColumnBase<ColumnMappingBase>("StockQuantity", "integer", monoSliceModulesCatalogDomainProductTableBase);
            monoSliceModulesCatalogDomainProductTableBase.Columns.Add("StockQuantity", stockQuantityColumnBase);
            var updatedAtColumnBase = new ColumnBase<ColumnMappingBase>("UpdatedAt", "timestamp with time zone", monoSliceModulesCatalogDomainProductTableBase)
            {
                IsNullable = true
            };
            monoSliceModulesCatalogDomainProductTableBase.Columns.Add("UpdatedAt", updatedAtColumnBase);
            relationalModel.DefaultTables.Add("MonoSlice.Modules.Catalog.Domain.Product", monoSliceModulesCatalogDomainProductTableBase);
            var monoSliceModulesCatalogDomainProductMappingBase = new TableMappingBase<ColumnMappingBase>(product, monoSliceModulesCatalogDomainProductTableBase, null);
            monoSliceModulesCatalogDomainProductTableBase.AddTypeMapping(monoSliceModulesCatalogDomainProductMappingBase, false);
            defaultTableMappings.Add(monoSliceModulesCatalogDomainProductMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, product.FindProperty("Id")!, monoSliceModulesCatalogDomainProductMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase, product.FindProperty("CreatedAt")!, monoSliceModulesCatalogDomainProductMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)descriptionColumnBase, product.FindProperty("Description")!, monoSliceModulesCatalogDomainProductMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isActiveColumnBase, product.FindProperty("IsActive")!, monoSliceModulesCatalogDomainProductMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, product.FindProperty("Name")!, monoSliceModulesCatalogDomainProductMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)priceColumnBase, product.FindProperty("Price")!, monoSliceModulesCatalogDomainProductMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)skuColumnBase, product.FindProperty("Sku")!, monoSliceModulesCatalogDomainProductMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)stockQuantityColumnBase, product.FindProperty("StockQuantity")!, monoSliceModulesCatalogDomainProductMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)updatedAtColumnBase, product.FindProperty("UpdatedAt")!, monoSliceModulesCatalogDomainProductMappingBase);

            var tableMappings = new List<TableMapping>();
            product.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var productsTable = new Table("Products", "catalog", relationalModel);
            var idColumn = new Column("Id", "uuid", productsTable);
            productsTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn);
            var createdAtColumn = new Column("CreatedAt", "timestamp with time zone", productsTable);
            productsTable.Columns.Add("CreatedAt", createdAtColumn);
            createdAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(createdAtColumn);
            var descriptionColumn = new Column("Description", "character varying(1000)", productsTable)
            {
                IsNullable = true
            };
            productsTable.Columns.Add("Description", descriptionColumn);
            descriptionColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(descriptionColumn);
            var isActiveColumn = new Column("IsActive", "boolean", productsTable);
            productsTable.Columns.Add("IsActive", isActiveColumn);
            isActiveColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(isActiveColumn);
            var nameColumn = new Column("Name", "character varying(200)", productsTable);
            productsTable.Columns.Add("Name", nameColumn);
            nameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn);
            var priceColumn = new Column("Price", "numeric(18,2)", productsTable);
            productsTable.Columns.Add("Price", priceColumn);
            priceColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<decimal>(priceColumn);
            var skuColumn = new Column("Sku", "character varying(50)", productsTable);
            productsTable.Columns.Add("Sku", skuColumn);
            skuColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(skuColumn);
            var stockQuantityColumn = new Column("StockQuantity", "integer", productsTable);
            productsTable.Columns.Add("StockQuantity", stockQuantityColumn);
            stockQuantityColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(stockQuantityColumn);
            var updatedAtColumn = new Column("UpdatedAt", "timestamp with time zone", productsTable)
            {
                IsNullable = true
            };
            productsTable.Columns.Add("UpdatedAt", updatedAtColumn);
            updatedAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(updatedAtColumn);
            relationalModel.Tables.Add(("Products", "catalog"), productsTable);
            var productsTableMapping = new TableMapping(product, productsTable, null);
            productsTable.AddTypeMapping(productsTableMapping, false);
            tableMappings.Add(productsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, product.FindProperty("Id")!, productsTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn, product.FindProperty("CreatedAt")!, productsTableMapping);
            RelationalModel.CreateColumnMapping(descriptionColumn, product.FindProperty("Description")!, productsTableMapping);
            RelationalModel.CreateColumnMapping(isActiveColumn, product.FindProperty("IsActive")!, productsTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, product.FindProperty("Name")!, productsTableMapping);
            RelationalModel.CreateColumnMapping(priceColumn, product.FindProperty("Price")!, productsTableMapping);
            RelationalModel.CreateColumnMapping(skuColumn, product.FindProperty("Sku")!, productsTableMapping);
            RelationalModel.CreateColumnMapping(stockQuantityColumn, product.FindProperty("StockQuantity")!, productsTableMapping);
            RelationalModel.CreateColumnMapping(updatedAtColumn, product.FindProperty("UpdatedAt")!, productsTableMapping);
            var pK_Products = new UniqueConstraint("PK_Products", productsTable, new[] { idColumn });
            productsTable.PrimaryKey = pK_Products;
            pK_Products.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_Products));
            var pK_ProductsKey = RelationalModel.GetKey(this,
                "MonoSlice.Modules.Catalog.Domain.Product",
                new[] { "Id" });
            pK_Products.MappedKeys.Add(pK_ProductsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_ProductsKey).Add(pK_Products);
            productsTable.UniqueConstraints.Add("PK_Products", pK_Products);
            var iX_Products_Sku = new TableIndex(
            "IX_Products_Sku", productsTable, new[] { skuColumn }, true);
            iX_Products_Sku.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_Products_Sku));
            var iX_Products_SkuIx = RelationalModel.GetIndex(this,
                "MonoSlice.Modules.Catalog.Domain.Product",
                new[] { "Sku" });
            iX_Products_Sku.MappedIndexes.Add(iX_Products_SkuIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Products_SkuIx).Add(iX_Products_Sku);
            productsTable.Indexes.Add("IX_Products_Sku", iX_Products_Sku);
            return relationalModel.MakeReadOnly();
        }
    }
}
