// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using MonoSlice.Shared.Abstractions.Domain;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MonoSlice.Modules.Catalog.Persistence.CompiledModels
{
    public static class EntityUnsafeAccessors<TId>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref TId Id(Entity<TId> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(Entity<TId> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UpdatedAt>k__BackingField")]
        public static extern ref DateTime? UpdatedAt(Entity<TId> @this);
    }
}
