// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using MonoSlice.Modules.Catalog.Domain;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MonoSlice.Modules.Catalog.Persistence.CompiledModels
{
    public static class ProductUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(Product @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsActive>k__BackingField")]
        public static extern ref bool IsActive(Product @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(Product @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Price>k__BackingField")]
        public static extern ref decimal Price(Product @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Sku>k__BackingField")]
        public static extern ref string Sku(Product @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StockQuantity>k__BackingField")]
        public static extern ref int StockQuantity(Product @this);
    }
}
