// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using MonoSlice.Modules.Catalog.Domain;
using MonoSlice.Shared.Abstractions.Domain;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MonoSlice.Modules.Catalog.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ProductEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "MonoSlice.Modules.Catalog.Domain.Product",
                typeof(Product),
                baseEntityType,
                propertyCount: 9,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(Entity<Guid>).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Entity<Guid>).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (Product instance) => EntityUnsafeAccessors<Guid>.Id(instance),
                bool (Product instance) => EntityUnsafeAccessors<Guid>.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                Product (Product instance, Guid value) =>
                {
                    EntityUnsafeAccessors<Guid>.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                Product (Product instance, Guid value) =>
                {
                    EntityUnsafeAccessors<Guid>.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && EntityUnsafeAccessors<Guid>.Id(((Product)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : EntityUnsafeAccessors<Guid>.Id(((Product)(entry.Entity))))),
                Guid (IInternalEntry entry) => EntityUnsafeAccessors<Guid>.Id(((Product)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => ((object)v).GetHashCode(),
                    Guid (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTime),
                propertyInfo: typeof(Entity<Guid>).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Entity<Guid>).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            createdAt.SetGetter(
                DateTime (Product instance) => EntityUnsafeAccessors<Guid>.CreatedAt(instance),
                bool (Product instance) => EntityUnsafeAccessors<Guid>.CreatedAt(instance) == default(DateTime));
            createdAt.SetSetter(
                Product (Product instance, DateTime value) =>
                {
                    EntityUnsafeAccessors<Guid>.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetMaterializationSetter(
                Product (Product instance, DateTime value) =>
                {
                    EntityUnsafeAccessors<Guid>.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetAccessors(
                DateTime (IInternalEntry entry) => EntityUnsafeAccessors<Guid>.CreatedAt(((Product)(entry.Entity))),
                DateTime (IInternalEntry entry) => EntityUnsafeAccessors<Guid>.CreatedAt(((Product)(entry.Entity))),
                DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(createdAt, 1),
                DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(createdAt));
            createdAt.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAt.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
                comparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v),
                keyComparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v),
                providerValueComparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v));
            createdAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(Product).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Product).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1000);
            description.SetGetter(
                string (Product instance) => ProductUnsafeAccessors.Description(instance),
                bool (Product instance) => ProductUnsafeAccessors.Description(instance) == null);
            description.SetSetter(
                Product (Product instance, string value) =>
                {
                    ProductUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetMaterializationSetter(
                Product (Product instance, string value) =>
                {
                    ProductUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetAccessors(
                string (IInternalEntry entry) => ProductUnsafeAccessors.Description(((Product)(entry.Entity))),
                string (IInternalEntry entry) => ProductUnsafeAccessors.Description(((Product)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(description, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(description));
            description.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            description.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "character varying(1000)",
                    size: 1000));
            description.TypeMapping = ((NpgsqlStringTypeMapping)description.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
        description.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var isActive = runtimeEntityType.AddProperty(
            "IsActive",
            typeof(bool),
            propertyInfo: typeof(Product).GetProperty("IsActive", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Product).GetField("<IsActive>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: false);
        isActive.SetGetter(
            bool (Product instance) => ProductUnsafeAccessors.IsActive(instance),
            bool (Product instance) => ProductUnsafeAccessors.IsActive(instance) == false);
        isActive.SetSetter(
            Product (Product instance, bool value) =>
            {
                ProductUnsafeAccessors.IsActive(instance) = value;
                return instance;
            });
        isActive.SetMaterializationSetter(
            Product (Product instance, bool value) =>
            {
                ProductUnsafeAccessors.IsActive(instance) = value;
                return instance;
            });
        isActive.SetAccessors(
            bool (IInternalEntry entry) => ProductUnsafeAccessors.IsActive(((Product)(entry.Entity))),
            bool (IInternalEntry entry) => ProductUnsafeAccessors.IsActive(((Product)(entry.Entity))),
            bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(isActive, 3),
            bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(isActive));
        isActive.SetPropertyIndexes(
            index: 3,
            originalValueIndex: 3,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        isActive.TypeMapping = NpgsqlBoolTypeMapping.Default.Clone(
            comparer: new ValueComparer<bool>(
                bool (bool v1, bool v2) => v1 == v2,
                int (bool v) => ((object)v).GetHashCode(),
                bool (bool v) => v),
            keyComparer: new ValueComparer<bool>(
                bool (bool v1, bool v2) => v1 == v2,
                int (bool v) => ((object)v).GetHashCode(),
                bool (bool v) => v),
            providerValueComparer: new ValueComparer<bool>(
                bool (bool v1, bool v2) => v1 == v2,
                int (bool v) => ((object)v).GetHashCode(),
                bool (bool v) => v));
        isActive.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var name = runtimeEntityType.AddProperty(
            "Name",
            typeof(string),
            propertyInfo: typeof(Product).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Product).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            maxLength: 200);
        name.SetGetter(
            string (Product instance) => ProductUnsafeAccessors.Name(instance),
            bool (Product instance) => ProductUnsafeAccessors.Name(instance) == null);
        name.SetSetter(
            Product (Product instance, string value) =>
            {
                ProductUnsafeAccessors.Name(instance) = value;
                return instance;
            });
        name.SetMaterializationSetter(
            Product (Product instance, string value) =>
            {
                ProductUnsafeAccessors.Name(instance) = value;
                return instance;
            });
        name.SetAccessors(
            string (IInternalEntry entry) => ProductUnsafeAccessors.Name(((Product)(entry.Entity))),
            string (IInternalEntry entry) => ProductUnsafeAccessors.Name(((Product)(entry.Entity))),
            string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 4),
            string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
        name.SetPropertyIndexes(
            index: 4,
            originalValueIndex: 4,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        name.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
            comparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            keyComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            providerValueComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "character varying(200)",
                size: 200));
        name.TypeMapping = ((NpgsqlStringTypeMapping)name.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
    name.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var price = runtimeEntityType.AddProperty(
        "Price",
        typeof(decimal),
        propertyInfo: typeof(Product).GetProperty("Price", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(Product).GetField("<Price>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        precision: 18,
        scale: 2,
        sentinel: 0m);
    price.SetGetter(
        decimal (Product instance) => ProductUnsafeAccessors.Price(instance),
        bool (Product instance) => ProductUnsafeAccessors.Price(instance) == 0M);
    price.SetSetter(
        Product (Product instance, decimal value) =>
        {
            ProductUnsafeAccessors.Price(instance) = value;
            return instance;
        });
    price.SetMaterializationSetter(
        Product (Product instance, decimal value) =>
        {
            ProductUnsafeAccessors.Price(instance) = value;
            return instance;
        });
    price.SetAccessors(
        decimal (IInternalEntry entry) => ProductUnsafeAccessors.Price(((Product)(entry.Entity))),
        decimal (IInternalEntry entry) => ProductUnsafeAccessors.Price(((Product)(entry.Entity))),
        decimal (IInternalEntry entry) => entry.ReadOriginalValue<decimal>(price, 5),
        decimal (IInternalEntry entry) => entry.GetCurrentValue<decimal>(price));
    price.SetPropertyIndexes(
        index: 5,
        originalValueIndex: 5,
        shadowIndex: -1,
        relationshipIndex: -1,
        storeGenerationIndex: -1);
    price.TypeMapping = NpgsqlDecimalTypeMapping.Default.Clone(
        comparer: new ValueComparer<decimal>(
            bool (decimal v1, decimal v2) => v1 == v2,
            int (decimal v) => ((object)v).GetHashCode(),
            decimal (decimal v) => v),
        keyComparer: new ValueComparer<decimal>(
            bool (decimal v1, decimal v2) => v1 == v2,
            int (decimal v) => ((object)v).GetHashCode(),
            decimal (decimal v) => v),
        providerValueComparer: new ValueComparer<decimal>(
            bool (decimal v1, decimal v2) => v1 == v2,
            int (decimal v) => ((object)v).GetHashCode(),
            decimal (decimal v) => v),
        mappingInfo: new RelationalTypeMappingInfo(
            storeTypeName: "numeric(18,2)",
            precision: 18,
            scale: 2));
    price.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var sku = runtimeEntityType.AddProperty(
        "Sku",
        typeof(string),
        propertyInfo: typeof(Product).GetProperty("Sku", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(Product).GetField("<Sku>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        maxLength: 50);
    sku.SetGetter(
        string (Product instance) => ProductUnsafeAccessors.Sku(instance),
        bool (Product instance) => ProductUnsafeAccessors.Sku(instance) == null);
    sku.SetSetter(
        Product (Product instance, string value) =>
        {
            ProductUnsafeAccessors.Sku(instance) = value;
            return instance;
        });
    sku.SetMaterializationSetter(
        Product (Product instance, string value) =>
        {
            ProductUnsafeAccessors.Sku(instance) = value;
            return instance;
        });
    sku.SetAccessors(
        string (IInternalEntry entry) => ProductUnsafeAccessors.Sku(((Product)(entry.Entity))),
        string (IInternalEntry entry) => ProductUnsafeAccessors.Sku(((Product)(entry.Entity))),
        string (IInternalEntry entry) => entry.ReadOriginalValue<string>(sku, 6),
        string (IInternalEntry entry) => entry.GetCurrentValue<string>(sku));
    sku.SetPropertyIndexes(
        index: 6,
        originalValueIndex: 6,
        shadowIndex: -1,
        relationshipIndex: -1,
        storeGenerationIndex: -1);
    sku.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
        comparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        keyComparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        providerValueComparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        mappingInfo: new RelationalTypeMappingInfo(
            storeTypeName: "character varying(50)",
            size: 50));
    sku.TypeMapping = ((NpgsqlStringTypeMapping)sku.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
sku.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(sku));
sku.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var stockQuantity = runtimeEntityType.AddProperty(
    "StockQuantity",
    typeof(int),
    propertyInfo: typeof(Product).GetProperty("StockQuantity", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(Product).GetField("<StockQuantity>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    sentinel: 0);
stockQuantity.SetGetter(
    int (Product instance) => ProductUnsafeAccessors.StockQuantity(instance),
    bool (Product instance) => ProductUnsafeAccessors.StockQuantity(instance) == 0);
stockQuantity.SetSetter(
    Product (Product instance, int value) =>
    {
        ProductUnsafeAccessors.StockQuantity(instance) = value;
        return instance;
    });
stockQuantity.SetMaterializationSetter(
    Product (Product instance, int value) =>
    {
        ProductUnsafeAccessors.StockQuantity(instance) = value;
        return instance;
    });
stockQuantity.SetAccessors(
    int (IInternalEntry entry) => ProductUnsafeAccessors.StockQuantity(((Product)(entry.Entity))),
    int (IInternalEntry entry) => ProductUnsafeAccessors.StockQuantity(((Product)(entry.Entity))),
    int (IInternalEntry entry) => entry.ReadOriginalValue<int>(stockQuantity, 7),
    int (IInternalEntry entry) => entry.GetCurrentValue<int>(stockQuantity));
stockQuantity.SetPropertyIndexes(
    index: 7,
    originalValueIndex: 7,
    shadowIndex: -1,
    relationshipIndex: -1,
    storeGenerationIndex: -1);
stockQuantity.TypeMapping = IntTypeMapping.Default.Clone(
    comparer: new ValueComparer<int>(
        bool (int v1, int v2) => v1 == v2,
        int (int v) => v,
        int (int v) => v),
    keyComparer: new ValueComparer<int>(
        bool (int v1, int v2) => v1 == v2,
        int (int v) => v,
        int (int v) => v),
    providerValueComparer: new ValueComparer<int>(
        bool (int v1, int v2) => v1 == v2,
        int (int v) => v,
        int (int v) => v),
    mappingInfo: new RelationalTypeMappingInfo(
        storeTypeName: "integer"));
stockQuantity.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var updatedAt = runtimeEntityType.AddProperty(
    "UpdatedAt",
    typeof(DateTime?),
    propertyInfo: typeof(Entity<Guid>).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(Entity<Guid>).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    nullable: true);
updatedAt.SetGetter(
    DateTime? (Product instance) => EntityUnsafeAccessors<Guid>.UpdatedAt(instance),
    bool (Product instance) => !(EntityUnsafeAccessors<Guid>.UpdatedAt(instance).HasValue));
updatedAt.SetSetter(
    Product (Product instance, DateTime? value) =>
    {
        EntityUnsafeAccessors<Guid>.UpdatedAt(instance) = value;
        return instance;
    });
updatedAt.SetMaterializationSetter(
    Product (Product instance, DateTime? value) =>
    {
        EntityUnsafeAccessors<Guid>.UpdatedAt(instance) = value;
        return instance;
    });
updatedAt.SetAccessors(
    DateTime? (IInternalEntry entry) => EntityUnsafeAccessors<Guid>.UpdatedAt(((Product)(entry.Entity))),
    DateTime? (IInternalEntry entry) => EntityUnsafeAccessors<Guid>.UpdatedAt(((Product)(entry.Entity))),
    DateTime? (IInternalEntry entry) => entry.ReadOriginalValue<DateTime?>(updatedAt, 8),
    DateTime? (IInternalEntry entry) => entry.GetCurrentValue<DateTime?>(updatedAt));
updatedAt.SetPropertyIndexes(
    index: 8,
    originalValueIndex: 8,
    shadowIndex: -1,
    relationshipIndex: -1,
    storeGenerationIndex: -1);
updatedAt.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
    comparer: new ValueComparer<DateTime>(
        bool (DateTime v1, DateTime v2) => v1.Equals(v2),
        int (DateTime v) => ((object)v).GetHashCode(),
        DateTime (DateTime v) => v),
    keyComparer: new ValueComparer<DateTime>(
        bool (DateTime v1, DateTime v2) => v1.Equals(v2),
        int (DateTime v) => ((object)v).GetHashCode(),
        DateTime (DateTime v) => v),
    providerValueComparer: new ValueComparer<DateTime>(
        bool (DateTime v1, DateTime v2) => v1.Equals(v2),
        int (DateTime v) => ((object)v).GetHashCode(),
        DateTime (DateTime v) => v));
updatedAt.SetComparer(new NullableValueComparer<DateTime>(updatedAt.TypeMapping.Comparer));
updatedAt.SetKeyComparer(new NullableValueComparer<DateTime>(updatedAt.TypeMapping.KeyComparer));
updatedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var key = runtimeEntityType.AddKey(
    new[] { id });
runtimeEntityType.SetPrimaryKey(key);

var index = runtimeEntityType.AddIndex(
    new[] { sku },
    unique: true);

return runtimeEntityType;
}

public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
{
    var id = runtimeEntityType.FindProperty("Id");
    var createdAt = runtimeEntityType.FindProperty("CreatedAt");
    var description = runtimeEntityType.FindProperty("Description");
    var isActive = runtimeEntityType.FindProperty("IsActive");
    var name = runtimeEntityType.FindProperty("Name");
    var price = runtimeEntityType.FindProperty("Price");
    var sku = runtimeEntityType.FindProperty("Sku");
    var stockQuantity = runtimeEntityType.FindProperty("StockQuantity");
    var updatedAt = runtimeEntityType.FindProperty("UpdatedAt");
    var key = runtimeEntityType.FindKey(new[] { id });
    key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
    key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
    runtimeEntityType.SetOriginalValuesFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType = ((Product)(source.Entity));
            return ((ISnapshot)(new Snapshot<Guid, DateTime, string, bool, string, decimal, string, int, DateTime?>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), ((ValueComparer<DateTime>)(((IProperty)createdAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(createdAt)), (source.GetCurrentValue<string>(description) == null ? null : ((ValueComparer<string>)(((IProperty)description).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(description))), ((ValueComparer<bool>)(((IProperty)isActive).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(isActive)), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), ((ValueComparer<decimal>)(((IProperty)price).GetValueComparer())).Snapshot(source.GetCurrentValue<decimal>(price)), (source.GetCurrentValue<string>(sku) == null ? null : ((ValueComparer<string>)(((IProperty)sku).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(sku))), ((ValueComparer<int>)(((IProperty)stockQuantity).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(stockQuantity)), (source.GetCurrentValue<DateTime?>(updatedAt) == null ? null : ((ValueComparer<DateTime?>)(((IProperty)updatedAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime?>(updatedAt))))));
        });
    runtimeEntityType.SetStoreGeneratedValuesFactory(
        ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid))))));
    runtimeEntityType.SetTemporaryValuesFactory(
        ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
    runtimeEntityType.SetShadowValuesFactory(
        ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
    runtimeEntityType.SetEmptyShadowValuesFactory(
        ISnapshot () => Snapshot.Empty);
    runtimeEntityType.SetRelationshipSnapshotFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType = ((Product)(source.Entity));
            return ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)))));
        });
    runtimeEntityType.SetCounts(new PropertyCounts(
        propertyCount: 9,
        navigationCount: 0,
        complexPropertyCount: 0,
        complexCollectionCount: 0,
        originalValueCount: 9,
        shadowCount: 0,
        relationshipCount: 1,
        storeGeneratedCount: 1));
    runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
    runtimeEntityType.AddAnnotation("Relational:Schema", "catalog");
    runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
    runtimeEntityType.AddAnnotation("Relational:TableName", "Products");
    runtimeEntityType.AddAnnotation("Relational:ViewName", null);
    runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

    Customize(runtimeEntityType);
}

static partial void Customize(RuntimeEntityType runtimeEntityType);
}
}
